overrides.nix

Nothing overly exciting - just sorted all overrides by name. Makes it more convenient/easier to spot what is there..
Also removed the `composeOverrides` function since that wasn't being used at all (only once where only one override was specified..)

Sort overrides by python package

---

default.nix
overrides.nix
tests/override-support/default.nix

Motivation:
- It's possible to add new packages via overrides
- It's easier to compose overrides
cc @stolyaroleh

Restrucure overrides as composable overlays

---

bin/poetry2nix
cli.nix
default.nix
tests/default.nix
tests/git-deps-pinned/default.nix
tests/git-deps-pinned/poetry-git-overlay.nix
tests/git-deps-pinned/poetry.lock
tests/git-deps-pinned/pyproject.toml

This is not required for private repos where builtins.fetchGit would
suffice but _is_ required for Hydra (nixpkgs) where builtins.fetchGit is not allowed.

Add CLI to supplement git hashes

---

default.nix
lib.nix
mk-poetry-dep.nix
pyproject-without-path.py
tests/default.nix
tests/override-support/default.nix
tests/path-deps/default.nix
tests/path-deps/poetry.lock
tests/path-deps/pyproject.toml

Add support for local path dependencies

---

extensions.json
generate.py
mk-poetry-dep.nix
tests/default.nix
tests/eggs/default.nix
tests/eggs/eggs.py
tests/eggs/poetry.lock
tests/eggs/pyproject.toml

Add support for eggs

---

overrides.nix

Add setuptools_scm build input for black

---

mk-poetry-dep.nix
overrides.nix
tests/default.nix
tests/prefer-wheel/default.nix
tests/prefer-wheel/poetry.lock
tests/prefer-wheel/pyproject.toml

Previously override wasn't really useful as it inherited the args from
buildPythonPackage.
Now we can create custom args for overrides.

Add preferWheel option to <derivation>.override

---

default.nix
lib.nix
mk-poetry-dep.nix
tests/default.nix
tests/path-deps-level2/default.nix
tests/path-deps-level2/poetry.lock
tests/path-deps-level2/pyproject.toml

This setup seems to work with poetry but not poetry2nix. We'll have a look at solving it, because we need to set up our build deps (in a monorepo) this way, but any comments/pointers are very welcome.

Handle two-layer inclusion of "path" dependencies

---

README.md

This provides a more complete API documetnation covering the public
interface of poetry2nix

Provide API documentation in README

---

overrides.nix

This adds overrides for the following python packages
- astroid
- h5py
- jupyter
- openexr
- rockset
- tensorpack

Add more overrides

---

overrides.nix

This adds an override fixing [tables](https://pypi.org/project/tables/)

Add tables override

---

README.md
default.nix
lib.nix
mk-poetry-dep.nix
tests/default.nix
tests/source-filter/.gitignore
tests/source-filter/default.nix
tests/source-filter/poetry.lock
tests/source-filter/pyproject.toml
tests/trivial/default.nix

Adds a default source filter when `projectDir` is used
Also use the same source filter for path deps.
The default source filter currently filters:
- Filters gitignore (if it exists, non-recursive)
- Filters pycache/pyc files
- Uses cleanSourceFilter to filter out .git/.hg, .o/.so, editor backup files & nix result symlinks

Set `src` to `cleanPythonSources projectDir` by default

---

default.nix

Do not leak projectDir into expressions

---

default.nix
mk-poetry-dep.nix

Fix git dependencies on non-default branches

---

default.nix
lib.nix
mk-poetry-dep.nix
tests/canonical-module-names/default.nix
tests/canonical-module-names/poetry-git-overlay.nix
tests/canonical-module-names/poetry.lock
tests/canonical-module-names/pyproject.toml
tests/default.nix

This shouldn't be required and I think that these are actually packaging bugs and not something that poetry2nix should really be concerned with.
With that said, if it works in Poetry the same lock file should also work in Poetry2nix.
Closes #84
cc @Infinisil @domenkozar

Add canonicalisation of module names

---

overrides.nix
tests/default.nix
tests/wandb/default.nix
tests/wandb/poetry.lock
tests/wandb/pyproject.toml

This PR adds a failing test case for the `wandb` package:                                                                                                                                                            
```                                                                                                                                                                                                                  
ERROR: Could not find a version that satisfies the requirement configparser>=3.8.1 (from wandb==0.8.28) (from versions: none)                                                                                        
ERROR: No matching distribution found for configparser>=3.8.1 (from wandb==0.8.28) …
```

Fix wandb build by setting configparser version

---

overrides.nix

Sorry, I'm an idiot. Fixes mistake in #96.

Fix isort override

---

README.md

Add docs for the change in https://github.com/nix-community/poetry2nix/pull/95
[Rendered](https://github.com/Infinisil/poetry2nix/tree/dependencyEnvDocs#dependency-environment)
Ping @gilligan @adisbladis

Add docs for dependencyEnv passthru

---

pep425.nix

The CPython stable ABI is abi3 as in the shared library suffix.
Closes #117

Fix wheel compatibility checks when abi is abi3

---

overrides.nix

Fix tensorflow collision with tensorboard

---

default.nix
overrides.nix
plugins.nix

This API is not to be considered stable or done by any means, I'd really like to figure out a better API.
In the interim I will merge this quickly so we can use it for NixOps.

Add experimental support for plugin closures

---

overrides.nix

This should fix #146 
closes #146

Added openssl dependency to psycopg2 on Darwin.

---

default.nix
hooks/default.nix
hooks/wheel-unpack-hook.sh
overrides.nix

This breaks as nixpkgs has updated it's wheel package

overrides: Remove condition from wheel override

---

overrides.nix

I've tested this out and it works. I'm happy to add a formal test to the repo too, but not sure exactly what the right way to test this is.

Override for dictdiffer

---

flake.nix

I've been experimenting with flakes.

improving flake experience

---

tests/git-deps-pinned/poetry.lock
tests/git-deps-pinned/pyproject.toml

rev / branch was not tested.
and rename git-deps to git-deps-pinned to prevent the confusion between
2 tests

feat: test tag/rev/branch

---

default.nix
editable.nix
hooks/default.nix
lib.nix
mk-poetry-dep.nix
nix/sources.json
nix/sources.nix
overrides.nix
pep425.nix
pep508.nix
pkgs/poetry/default.nix
pkgs/poetry/poetry.lock
pkgs/poetry/pyproject.toml
pkgs/poetry/src.json
tests/default.nix

Closes https://github.com/nix-community/poetry2nix/issues/172
Closes https://github.com/nix-community/poetry2nix/issues/163

poetry: 1.0.10 -> 1.1.0

---

overrides.nix

These are two overrides I find missing when migrate my project to nix.

add missing overrides

---

overrides.nix

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/supervisor/default.nix#L25

add overrides for supervisor

---

overrides.nix

Mostly aggregating the suggestions from
https://github.com/nix-community/poetry2nix/issues/69.
Fixes #69.

Add an override for torch

---

pkgs/poetry/pyproject.toml
pkgs/poetry/src.json
shell.nix

Fixes https://github.com/nix-community/poetry2nix/issues/201

Bumped poetry to version 1.1.4

---

mk-poetry-dep.nix
overrides.nix
pkgs/poetry/default.nix

Make poetry2nix builds work when cross compiling.

fix cross builds

---

bin/poetry2nix
mk-poetry-dep.nix
shell.nix

depends on https://github.com/nix-community/poetry2nix/pull/204

Support source url type

---

flake.lock
flake.nix

reverts https://github.com/nix-community/poetry2nix/pull/210 and make it possible to use the flake via `nix run`.

Flake default app

---

overrides.nix

torch fix, fixes #230

---

overrides.nix

overrides: Pin pip to 20.2.4 to work around #244

---

overrides.nix

@adisbladis As discussed, here are the overrides that we have had to use.
This work has been sponsored by [niteoweb](https://github.com/niteoweb/)

Fixes by niteo

---

.github/workflows/ci.yml
nix/sources.json
overrides.nix
tests/default.nix

There has been a lot of test breakage recently that has nothing to do with `poetry2nix` itself. Let's re-pin nixpkgs to get tests more reliable.

Pin nixpkgs used for testing

---

overrides.nix

Fixes a problem that #223 tried to solve

Add libmysqlclient to mysqlclient's nativeBuildInputs

---

overrides.nix

This PR adds an override to torchvision and a change to torch override.

Add override to torchvision and a change to torch override

---

overrides.nix

It builds wxPython with GTK+3 backend. Tested with the wxPython demo.

Add overrides for wxPython

---

overrides.nix

Add override for pyproject-flake8

---

overrides.nix

See https://github.com/qmk/qmk_firmware/pull/12855

Additional overrides for packages used by qmk

---

overrides.nix

Yet another package that needs pbr :)

Add override for requests-unixsocket

---

.github/workflows/ci.yml
tests/git-deps-pinned/poetry-git-overlay.nix

To speed up CI runs by ensuring we don't need to copy so much data around.

Use nix-build-uncached in CI

---

README.md
flake.nix
templates/app/flake.nix

Provide a basic flake template for building a Python application.

Provide flake template for building an app

---

overrides.nix

Based on
<https://github.com/nix-community/poetry2nix/issues/322#issuecomment-874944931>
Closes #322 together with #366.

feat: Make ruamel-yaml installable

---

overrides.nix

Based on
<https://github.com/nix-community/poetry2nix/issues/322#issue-922199285>.
Closes #322 together with #365.

feat: Make pytest-randomly installable

---

tests/default.nix
tests/in-list/default.nix
tests/in-list/poetry.lock
tests/in-list/pyproject.toml

Tests the change in commit 203fb43910143e926ad80e08a3d0bb46130c49ec.
See https://github.com/nix-community/poetry2nix/issues/360#issuecomment-906911264

tests: Add `in` test

---

README.md

Remove repeated section in README

---

.github/workflows/ci.yml

- ci: add nix-command to nix's experimental features
- ci: cachix/install-nix-action v13 -> v14
- ci: cachix/cachix-action v8 -> v10
- ci: actions/checkout v1 -> v2.4.0

ci: update actions and fix nix install

---

overrides.nix

This PR should be merged after https://github.com/nix-community/poetry2nix/pull/430.

Fix cloudflare output examples/__init__.py collision

---

overrides.nix

Handled by platformdirs override.

feat: Remove obsolete virtualenv override

---

overrides.nix

[The latest version builds](https://gitlab.com/victor-engmark/mypy-exercises/-/jobs/1733748482) (search for "Successfully installed mypy-0.910").

feat: Re-enable mypyc from version 0.910

---

overrides.nix

add absl-py as tensorboard dependency

---

overrides.nix
tests/default.nix
tests/jq/default.nix
tests/jq/poetry.lock
tests/jq/pyproject.toml

fix: patch jq to remove requests and depend on upstream jq

---

.github/generate-matrix.py
.github/workflows/ci.yml

Currently the output is unreadable (I have no idea without digging _what_ test failed).

Switch testing strategy on Github Actions to one based on a dynamic matrix

---

.github/ISSUE_TEMPLATE/issue-template.md

And urge people not to create issues for things which aren't
actionable for us as poetry2nix maintainers.

Add a github issue template

---

default.nix

I want a CI run before tagging this release.

Bump version to 1.24.1

---

hooks/pyproject-without-special-deps.py
tests/aiopath/default.nix
tests/aiopath/poetry.lock
tests/aiopath/pyproject.toml
tests/default.nix

- test: add failing aiopath test
- fix: set ensure_ascii to False because utf8 is legit

fix: don't force json.dump output to be ASCII

---

overrides.nix

Since I no longer trust nixpkgs to not break python packages for me I will start vendoring them in my NixOS configuration.

Add overrides to build pantalaimon

---

overrides.nix

Add override to satisfy [bjoern](https://github.com/jonashaag/bjoern)'s libev dependency.

overrides: Add bjoern override

---

.github/workflows/ci.yml
fetch_from_legacy.py
generate.py
hooks/pyproject-without-special-deps.py
shell.nix
tests/dependency-environment/trivial.py
tests/editable-egg/src/trivial/__init__.py
tests/eggs/eggs.py
tools/default.nix
tools/poetry.lock
tools/pyproject.toml

This also (somewhat unrelated) adds black formatting and checks.

Various fixes and checks for python2 compatibility

---

overrides.nix

Closes #303
@bbenne10 this was your fix so I set you as co-author, let me know if that's an issue. I'll mark as draft until you sign off.

overrides.flatbuffers: add override

---

overrides.nix

Sorry for the PR spam, I would have bundled this with the pyrfr override but I forgot about it.

 overrides.pymssql: add override

---

default.nix
mk-poetry-dep.nix
pkgs/poetry/default.nix

Since #466 was merged we don't need it anymore.

Remove __isBootstrap hack

---

default.nix
lib.nix
mk-poetry-dep.nix
overrides.nix
pep425.nix
pep508.nix
tests/default.nix
tests/trivial-cross/default.nix
tests/trivial-cross/poetry.lock
tests/trivial-cross/pyproject.toml

Fix cross compilation and add cross test

---

overrides.nix

Split into two commits to kinda keep related stuff together.

Add some overrides

---

tests/assorted-pkgs/default.nix
tests/assorted-pkgs/poetry.lock
tests/assorted-pkgs/pyproject.toml
tests/default.nix

I intend to add smaller test cases here that are not big enough to warrant their own tests.

Add assorted-pkgs test

---

.github/ISSUE_TEMPLATE/issue-template.md
docs/edgecases.md

Also corresponding changes in issue template to
reference new document.

Document explaining known issues with python packages

---

overrides/build-systems.json

This PR adds a few more build systems for packages that need them.

Add more build systems

---

overrides/build-systems.json

This PRs adds more build systems overrides

Add more build systems overrides

---

docs/edgecases.md
overrides/build-systems.json
overrides/default.nix

I recently started a new poetry2nix-based project and these are the overrides I needed. 
Tested in our CI on Linux and macOS.

A few fixes to various packages

---

mk-poetry-dep.nix

Fix infinite recursion in project with flit-core

---

overrides/build-systems.json

testpath: Use flit as a build system

---

overrides/build-systems.json
overrides/default.nix
tests/default.nix
tests/utf8-pyproject/default.nix
tests/utf8-pyproject/poetry.lock
tests/utf8-pyproject/pyproject.toml

fix utf8 parsing of strawberry-graphql and add confluent-kafka

---

overrides/build-systems.json
overrides/default.nix

A few more fixes I found when working on a new project.
Again tested in our CI on Linux and macOS.

More various fixes

---

overrides/default.nix

I'm really tired of the situation where we have to play catch-up with
upstream's Rust shenanigans.
While this is not a true fix it should at least help some people not
to break their setups whenever upstream decides to cut a new release.

overrides.cryptography: Prefer wheel if we don't have a pinned cargo hash

---

overrides/default.nix

overrides: pillow: Add libxcb libX11

---

overrides/build-systems.json

- build-systems.json: add poetry-dynamic-versioning
- build-systems.json: add pyparsing

build systems

---

overrides/default.nix

Added override for the orjson package.

orjson override

---

overrides/build-systems.json
overrides/default.nix
tools/find-build-systems.py

This should also fix https://github.com/nix-community/poetry2nix/issues/564.

datadog package and hatch support

---

README.md

I realize that people do not know of `preferWheels` and here is a simple attempt to document it.

Document preferWheels parameter

---

nix/sources.json
overrides/build-systems.json
overrides/default.nix
tests/default.nix
tools/find-build-systems.py

I also snuck in a Pandas override that should fix the build on non-linux (which I haven't been able to test).

Sync build systems (2022-05-05)

---

.github/workflows/ci.yml
shell.nix

Various minor quality of life improvements, especially for larger rebuilds where each build invocation would take an excessively long time.

Improve CI performance

---

.github/workflows/ci.yml

First I need to extract the key, then we'll hard code it.
I want PRs to also be able to use the cache so contributors can iterate.
This cache is not for public consumption anyway, so there are no trust issues to consider.

CI: Hard code cachix key in workflow yaml

---

overrides/default.nix
tests/default.nix
tests/pyqt5/default.nix
tests/pyqt5/poetry.lock
tests/pyqt5/pyproject.toml

Fixes https://github.com/nix-community/poetry2nix/issues/631.

overrides.pyqt5: Fix build with more recent QT versions

---

overrides/default.nix

I managed to miss this on my previous PR. My apologies!

overrides.lightgbm: add temporary home directory for source build

---

overrides/build-systems.json

[darglint](https://github.com/terrencepreilly/darglint) uses poetry for build.

build-systems: use poetry for darglint

---

overrides/build-systems.json
overrides/default.nix
pkgs/poetry/poetry.lock
pkgs/poetry/pyproject.toml
pkgs/poetry/src.json
tests/path-deps-develop/default.nix

I know that 1.2.0 is released by I would like to make this much smaller incremental step first.

poetry: 1.1.14 -> 1.1.15

---

overrides/build-systems.json

overrides: add contourpy, widgetsnbextension

---

overrides/build-systems.json

botocore-stubs override

---

overrides/build-systems.json

[cytoolz](https://pypi.org/project/cytoolz/) is a
> Cython implementation of the [toolz](https://github.com/pytoolz/toolz) [package,](https://pypi.python.org/pypi/toolz/) which provides high performance utility functions for iterables, functions, and dictionaries.

build-systems: add cytoolz

---

overrides/build-systems.json
overrides/default.nix

As I couldn't force push the cleaned up version with the new tests removed (they take too long to run and didn't really add value) I'm creating another PR.
Closes #752.

some missing overrides (#752)

---

default.nix
overrides/build-systems.json
overrides/default.nix

Build system updates to nbconvert, nbformat and pydeprecate.

build-systems: nbconvert and pydeprecate

---

overrides/build-systems.json

#716 + aforementioned overrides

uvicorn, fastapi, manage-fastapi

---

overrides/default.nix
tests/default.nix

overrides: fix mypy build

---

default.nix
mk-poetry-dep.nix
nix/sources.json

…nPackages
This does technically break people that override hooks, but they deserve it.

fix: pull in hooks directly instead of sneaking them in through pythonPackages

---

overrides/build-systems.json
overrides/default.nix

Add some missing build system and fixes Open3D 0.16.0.

Add overrides

---

overrides/build-systems.json
overrides/default.nix

- tested in https://github.com/nazarewk-iac/nix-configs/commit/368ae661
- fixes #824

nicegui: init & fix structlog + watchfiles

---

overrides/build-systems.json

add setuptools to a few packages that need it

---

overrides/build-systems.json

```
Processing /build/tornado-utils-1.6
Running command Preparing metadata (pyproject.toml)
Processing /build/tornado-utils-1.6
Running command Preparing metadata (pyproject.toml)
Preparing metadata (pyproject.toml) ... done
ERROR: Exception:
Traceback (most recent call last):
File "/nix/store/5j3i9xprrhdmqy8ljq9qpq9amafsgrk6-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
status = run_func(*args)
File "/nix/store/5j3i9xprrhdmqy8ljq9qpq9amafsgrk6-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
return func(self, options, args)
File "/nix/store/5j3i9xprrhdmqy8ljq9qpq9amafsgrk6-python3.10-pip-22.2.2/lib/python3.10/site-packages/pip/_internal/commands/wheel.py", …
```

overrides: add setuptools to tornado-utils

---

overrides/default.nix

Adds the hash for watchfiles 0.18.1

overrides: watchfiles 0.18.1

---

nix/sources.json
overrides/build-systems.json
pkgs/poetry/poetry.lock
pkgs/poetry/pyproject.toml
pkgs/poetry/src.json

poetry: 1.2.2 -> 1.3.0

---

overrides/build-systems.json
overrides/default.nix

Fixes https://github.com/nix-community/poetry2nix/issues/768.
@moduon MT-1075

override: copier and pyyaml-include

---

overrides/build-systems.json
overrides/default.nix

Adds support for newer versions of mkdocs-material

mkdocs-material: support newer versions

---

overrides/build-systems.json
overrides/default.nix
tests/default.nix
tests/gdal/default.nix
tests/gdal/poetry.lock
tests/gdal/pyproject.toml
tests/rasterio/default.nix
tests/rasterio/poetry.lock
tests/rasterio/pyproject.toml

Fixes needed for https://github.com/linz/emergency-management-tools/pull/51 (and GDAL 3.6, which isn't available for Ubuntu 22.04).

build: Geospatial build systems part 2

---

overrides/default.nix
tests/nbconvert-wheel/default.nix

This PR makes sure to patch nbconvert when it is installed as a wheel so that the right template path exists.

patches for nbconvert

---

README.md

There might be a better place to document this (like an architecture section), but it's a start.

Document `sdist` behaviour

---

docs/edgecases.md

Helps with #921.
@adisbladis Is this an accurate explanation of the issue and solution?

docs: Explain setuptools-scm edge case

---

overrides/build-systems.json

See https://github.com/tomerfiliba/plumbum/releases/tag/v1.8.1

fix: plumbum 1.8.1 build systems

---

flake.nix
templates/app/flake.nix

See individual commit messages for reasoning. the template is now half the code it was before.

Modernize flake and simplify flake template

---

.github/dependabot.yml

fix: Point Dependabot to directory with poetry.lock file

---

overrides/build-systems.json

There's probably more, but these were necessary to get the project I'm working on to build.

fix: AWS CDK v1 build systems

---

overrides/default.nix

- Build system dependency (setuptools).
- Native library dependency path fixup.

overrides: add libarchive

---

overrides/build-systems.json
overrides/default.nix

fix(build-systems): add a few

---

overrides/build-systems.json
overrides/default.nix

This adds buildsystems for many bioinformatics / computational chemistry packages

chore: buildsystems for many scientific packages

---

default.nix

This was applied in nixpkgs in https://github.com/NixOS/nixpkgs/commit/17c15cc3ff1e51f2c3621589e8e6cc9d33826ae5

don't use poetry from nixpkgs

---

hooks/default.nix

This PR avoids the large number of warnings generated by makeSetupHook when using a recent nixpkgs.

chore: prevent makeSetupHook warning on later nixpkgs

---

overrides/default.nix

Fixes the dependencies in the title

Fix dbt-extractor and minimal-snowplow-tracker

---

overrides/default.nix

Adds override to allow building `databricks-connect`

Add override to handle databricks-connect

---

overrides/default.nix

This collides with the version built from pypi, and if the version mismatches the build process attempts an uninstall of the nixpkgs gdal package.
We can avoid this by only building the native library and ignore the Python bindings.
Closes #1065

overrides.gdal: disable python bindings in gdal from nixpkgs

---

hooks/pip-build-hook.sh
overrides/default.nix

I have to open a new PR as I can't force push to #974.

 feat: autofix version for all packages that use setuptools-scm (#974) 

---

overrides/build-systems.json

Just adding a few overrides I needed to use while packaging https://github.com/nathom/streamrip

add some overrides to build-systems.json

---

overrides/build-systems.json
overrides/default.nix

I'm not sure yet how this works, but my derivations works with those changes.
If it matters, that's the package
https://github.com/bclaud/julius
Thank youu

Python-multipart build-system, watchfiles and orjson overrides

---

overrides/build-systems.json

Adds build system overrides for dataclass-wizard, kubernetes-stub, types-dataclasses and types-paramiko.

Add a handful of build system overrides

---

overrides/build-systems.json

https://github.com/andialbrecht/sqlparse/pull/697

Starting with version 0.4.4 sqlparse uses flit for building

---

overrides/build-systems.json
overrides/default.nix

This PR upstreames overrides that we'd been using.
It goes on top of #1135

Buildsystems contributions

---

overrides/build-systems.json

upstream overrides for pdfalyzer package https://github.com/michelcrypt4d4mus/pdfalyzer

overrides: for packages to build pdfalyzer

---

overrides/build-systems.json
overrides/default.nix

Add overrides for
cysystemd
pem
pip-licenses
python-pam
pythonping
tacacs-plus

Various module overrides

---

overrides/build-systems.json

Buildsystem contributions

---

overrides/build-systems.json
overrides/default.nix

Contributing our overrides

---

overrides/build-systems.json
overrides/default.nix

- overrides: add insights-core
- overrides: add pynetbox

Add overrides for `insights-core` and `pynetbox`

---

overrides/build-systems.json

https://github.com/gazpachoking/jsonref/commit/9faf61eb8

Switch jsonref to pdm

---

overrides/default.nix

Fixes https://github.com/nix-community/poetry2nix/issues/1162

prevent dependency cycle when installing textual

---

overrides/default.nix

Dear maintainers,
This commit updates the LLVM version (to the LLVM 14) that the most recent `llvmlite` release uses. Without this update, the most recent `numba` release will raise an error a-la "please build `llvmlite` with LLVM 14" on import.
I also cleaned up the related code, which chooses the LLVM version. Also, now the chosen LLVM sets the `llvm` attribute of the `llvmlite` derivation, and only the `self.llvmlite.llvm` package is added to the `nativeBuildInputs`, to make the `llvm` attribute overridable.

Update the llvmlite override

---

overrides/default.nix

Workaround for https://github.com/nix-community/poetry2nix/issues/1161, while we investigate the root cause.

eth-utils: prefer wheel

---

overrides/build-systems.json

https://github.com/RDFLib/rdflib/releases/tag/6.3.0
https://github.com/RDFLib/rdflib/pull/2187

added overrides for rdflib

---

mk-poetry-dep.nix

The submodule argument was introduced in version >= 2.4

Fix backwards incompatibility in fetchGit

---

overrides/build-systems.json

Is this the correct way repair these packages for problem #736 ?

Update build-systems.json repath, flet, flet-core

---

overrides/build-systems.json

fix(find-git-repos): add build system

---

.github/workflows/ci.yml

Add collect job to enable a status check.

ci: make job to collect all upstream jobs to enable a status check

---

overrides/build-systems.json

A simple package, with its niched usage, I don't think a test is really necessary.
* Builds on my machine

Add ubersmith client

---

overrides/default.nix

Fix DuckDB 0.8

---

.github/ci.nix
.github/workflows/ci.yml
nix/sources.json
tests/default.nix

Using https://github.com/nix-community/nix-github-actions

Redefine Github Actions in Nix using nix-github-actions

---

overrides/build-systems.json

https://github.com/samuelcolvin/arq/blob/main/pyproject.toml

arq: add 'hatchling' override

---

overrides/default.nix

Thanks to #825 for giving me the clues to figure out and fix this one!

sqlmodel: Substitute correct version

---

overrides/build-systems.json

Resubmitted PR after changing name of downstream branch.

build-systems: update argon2-cffi

---

overrides/build-systems.json

What they have in common is that they are part of Langchain's deps.
This is a cutdown version of #1263 which hopefully passes CI.

Add overrides for various packages

---

overrides/build-systems.json

See [flask changelog](https://github.com/pallets/flask/blob/main/CHANGES.rst#version-233).

flask: setuptools -> flit-core for 2.3.3+

---

.github/PULL_REQUEST_TEMPLATE.md

docs: Contribution checklist as part of PR template

---

overrides/default.nix

resolves #1019
Patch found in nixpkgs for hidapi

Add overrides for hidapi

---

overrides/default.nix

rpds-py: update hash v0.10.5 and v0.10.6

---

.github/workflows/ci.yml
templates/app/flake.nix

fix(template): import poetry2nix instead of using legacyPackages

---

tests/awsume/poetry.lock
tests/awsume/pyproject.toml

test(awsume): pin psutil

---

README.md

Adds documentation for checkGroups attribute.
Resolves #1335 

chore: documentation for checkGroups (fixes #1335)

---

.github/workflows/ci.yml
flake.nix
templates/app/flake.nix

cleanup: reorganize flake a bit, export lib.mkPoetry2Nix as a function

---

dev/treefmt.nix

treefmt: Sort build systems

---

.github/workflows/ci.yml
flake.nix
tests/default.nix

Fixes CI matrix construction and overlay handling.

chore: ensure that ci fails when matrix construction errors

---

overrides/build-systems.json

overrides: add opencv-python-headless

---

overrides/build-systems.json

add flit-core to django-filter

---

overrides/build-systems.json

https://github.com/twisted/constantly/commit/caea17e7ac860bbe9d2d83055a6611932d4d2edc

overrides: fix constantly > 23.10.0

---

overrides/build-systems.json

Add opencv-contrib-python to build-systems.json

---

.github/workflows/ci.yml
flake.nix

fix(flake): app flake outputs now evaluates

---

overrides/build-systems.json

https://github.com/openai/openai-python/commit/08b8179a6b3e46ca8eb117f819cc6563ae74e27d

overrides: fix openai buildsystems

---

default.nix
mk-poetry-dep.nix
vendor/pyproject.nix/default.nix
vendor/pyproject.nix/fetchers/default.nix
vendor/pyproject.nix/lib/pep440.nix
vendor/pyproject.nix/lib/pep508.nix
vendor/pyproject.nix/lib/pep600.nix
vendor/pyproject.nix/lib/pep621.nix
vendor/pyproject.nix/lib/pep656.nix
vendor/pyproject.nix/lib/pypa.nix

vendor: Bump pyproject.nix

---

overrides/default.nix
tests/ruff/default.nix

Allow use of wheels with `ruff`

chore: fix ruff build

---

overrides/default.nix
tests/ruff/poetry.lock
tests/ruff/pyproject.toml

overrides: ruff 0.1.5

---

overrides/build-systems.json

- aiohttp-client-cache
- aiohttp-rpc
- toga
- toga-core
- toga-gtk
- travertino

fix(overrides): add several build system overrides

---

overrides/default.nix

Add a few overrides

---

overrides/build-systems.json

Overrides: heroicons, ptvsd, slippers, yamlfix

---

overrides/build-systems.json
overrides/default.nix

Fix latest mkdocs-material

---

overrides/build-systems.json

overrides: bolt11

---

overrides/build-systems.json

Added "licensing" package build system

---

overrides/build-systems.json

Added cryptocode

---

overrides/build-systems.json

overrides: add aiohttp-devtools

---

overrides/build-systems.json

overrides: flyteidl, flytekit

---

overrides/build-systems.json

overrides: add fastapi-sso, types-passlib, types-pyasn1, types-python-jose

---

overrides/build-systems.json

Added flask-continuum

---

overrides/build-systems.json

Added odata-query

---

overrides/build-systems.json

add new overrides build systems

---

overrides/build-systems.json

overrides: add xdoctest

---

.github/workflows/ci.yml

.github/workflows/ci.yml: set concurrency, max-parallel for nix-build

---

overrides/build-systems.json
overrides/default.nix

Overrides alembic-postgresql-enum, frozenlist, ruff and OTEL-sqlalchemy

---

overrides/build-systems.json

overrides: add pyiceberg and mmhash3

---

overrides/default.nix

rpds-py: update getCargoHash

---

overrides/build-systems.json

overrides: Add instagrapi

---

overrides/build-systems.json
overrides/default.nix

fix aiokafka and overrides fastapi-camelcase

---

overrides/build-systems.json

overrides: add pyrundeck

---

overrides/build-systems.json
overrides/default.nix

chore(build-system):  added more build systems and maturin to clarabel

---

overrides/build-systems.json

overrides: add fastapi-plugins

---

overrides/default.nix

fix: add rpds-py v0.18.0 cargoHash

---

overrides/default.nix

fix(psutil) v5.9.8

---

overrides/build-systems.json
tests/pep600/poetry.lock

build: add cython3 req to pandas >=2.2.2

---

overrides/build-systems.json

overrides: update build system for sqlparse 0.5.0 to hatchling

---

overrides/build-systems.json

fix: add build system info for `fastapi-users`, `fastapi-users-db-sqlalchemy`, and `pwdlib`

---

overrides/build-systems.json

Redux of #1595 rebased on `master`.

chore(build-system): method tools, mpire, maturing, dnspython

---

overrides/build-systems.json

`dnspython`: `setuptools` -> `hatchling` in 2.5.0+

---

overrides/build-systems.json

Redux of #1562 rebased on `master`.

overrides: add types-oauthlib and types-xmltodict

---

overrides/default.nix

pillow-heif: add pkg-config, fix #1540

---

README.md

@adisbladis 
@K900 
Feel free to modify, request changes or delete this PMR as you please.

Improve documentation: How to add private repositories with authentication

---

overrides/build-systems.json

Commit/PR formatted after #1622, can update formatting if incorrect

Mark google-search-results as needing setuptools

---

README.md
default.nix

- Address https://github.com/nix-community/poetry2nix/issues/627 by improving docs.
- Ensure the same default value is used for `checkGroup` default values by using a constant.

Fix checkgroups

---

.github/workflows/ci.yml

chore: push to cachix

---

.github/workflows/ci.yml

Disable concurrency. See [this comment](https://github.com/nix-community/poetry2nix/pull/1625#issuecomment-2102805576) for details.

ci: disable finer grained concurrency

---

overrides/build-systems.json

overrides: add build systems for several packages

---

.github/workflows/ci.yml
overrides/build-systems.json
overrides/default.nix

A bunch of formatting changes and some cleanup of optionalAttrs and branching, as well as moving some native build inputs to `build-systems.json`.

chore: clean up build systems and formatting in `overrides/default.nix`

---

README.md
docs/edgecases.md

docs: update documentation regarding the overlay

---

overrides/build-systems.json

Build overrides for `jsonschema2d`, `zipfile2`, `okonomiyaki`, `simplesat`, `fusesoc`

---

vendor/pyproject.nix/lib/pep508.nix

vendor: Upgrade pyproject.nix

---

overrides/default.nix

overrides: fix cryptography 43.0.0

---

overrides/build-systems.json

overrides: add ezgiphy (needs setuptools)

---

overrides/build-systems.json

overrides: add svcs (needs hatchling)

---

overrides/build-systems.json

overrides: add grpc-requests (needs setuptools)

---

overrides/build-systems.json

Overrides: add splink

---

overrides/build-systems.json

Add types overrides

---

overrides/build-systems.json

https://pypi.org/project/types-TgCrypto/

build-systems.json: Add types-tgcrypto

---

overrides/default.nix

overrides/default: add hash for rpds-py 0.19.1

---

overrides/build-systems.json

Adding the setuptools requirement for the package [typesense](https://pypi.org/project/typesense/)

Adding typesense to overrides

---

overrides/default.nix

overrides: add hash for rdps-py 0.20.0

---

README.md

docs: update README with flake format command

---

overrides/default.nix
tests/watchfiles/poetry.lock
tests/watchfiles/pyproject.toml

chore: bump watchfiles to 0.23.0

---

overrides/build-systems.json
overrides/default.nix

Assorted overrides

---

overrides/default.nix

Could you please take a look? @adisbladis

overrides: add cryptography 43.0.1

---

overrides/default.nix

overrides/orjson: work around IFD requirement

---

overrides/build-systems.json

fix(overrides): add build system deps for python3-discogs-client

---

overrides/build-systems.json

fix(scienceplots): add scienceplots to build-systems.json

---

overrides/build-systems.json

fix(overrides): polyfactory

---

overrides/build-systems.json

fix(overrides): litestar

---

overrides/build-systems.json

overrides: add uuid6, uuid7

---

overrides/build-systems.json
overrides/default.nix

fix(overrides): psycopg-c, asyncpg-stubs

---

templates/app/flake.nix

feat: more idiomatic template flake.nix

---

overrides/build-systems.json

overrides: add types-cffi

---

flake.lock

chore(deps): bump nixpkgs

---

overrides/build-systems.json

Adding a library as suggested by the edge case documentation

add pylightxl to build-systems.json

---

overrides/build-systems.json

Override build system for a few packages

---

overrides/build-systems.json
overrides/default.nix

This override is needed for [py4vasp](https://github.com/vasp-dev/py4vasp)

fix(overrides): add build system deps for nglview

---

overrides/build-systems.json

overrides: add vonage-utils

---

overrides/build-systems.json

fix(overrides): cron-converter

---

overrides/default.nix
tests/python-versions-or/poetry.lock
tests/python-versions-or/pyproject.toml

overrides: add cryptography 43.0.3

---

overrides/build-systems.json

feat(nepattern): override build-systems

---

overrides/build-systems.json

fix(daff): add setuptools for daff

---

overrides/build-systems.json

- [n/a] There's an _[automated test](tests/default.nix)_ for this change
- [n/a] Commit messages or code include _references to related issues or PRs_ (including third parties)

overrides: add suncalc

---

overrides/default.nix

overrides: add hash for rpds-py 0.20.1

---

overrides/default.nix

overrides: add google-re2

---

overrides/build-systems.json

overrides: add pzp

---

overrides/default.nix

overrides: add hash for rpds-py 0.21.0

---

flake.lock

Update lock file

---

overrides/build-systems.json
overrides/default.nix

Add additional overrides

---

overrides/default.nix
tests/cryptography/poetry.lock

overrides: Update cryptography to 44.0.2

---

overrides/default.nix

overrides: add setuptools for phonetics

---

overrides/build-systems.json

References:
- https://github.com/koxudaxi/datamodel-code-generator/releases/tag/0.27.0

overrides: Add datamodel-code-generator
