nix-community/poetry2nix

- default.nix
- overrides.nix
We already have the name of the file that we need, so let's fetch it
directly instead of breaking it apart first, passing it to the Nixpkgs
fetchPypi, which would then put it together again.
> simplify fetchPypi, remove need for overrides

- default.nix
- The first letter path segment in the url needs to be lowercased
https://files.pythonhosted.org/packages/source/S/sqlalchemy/SQLAlchemy-1.3.11.tar.gz
vs
https://files.pythonhosted.org/packages/source/s/sqlalchemy/SQLAlchemy-1.3.11.tar.gz
- Rename fetchPypi to fetchFromPypi just to make it clear that we are
not using fetchPypi from nixpkgs
> Fixes pypi fetching

- overrides.nix
I think this was a copy-paste oversight.
> Fix small mistake in override of vose-alias-method

- default.nix
Prevent Nix from copying the project directory to store by removing it
from args passed to `buildPythonApplication`.
> Do not depend on contents of pwd

- default.nix
- mk-poetry-dep.nix
- tests/closure-size/default.nix
- tests/closure-size/poetry.lock
- tests/closure-size/pyproject.toml
- tests/default.nix
- Make it possible to pass additional nativeBuildInputs to packages.
- Strip libraries and executables.
If they are not stripped, they will retain debug symbols that often reference compilers (standard library includes), or dev outputs (headers that are not needed at runtime).
- Put buildSystemPkgs in buildInputs instead of propagatedBuildInputs. This removes intreehooks and Poetry from runtime closure. During fixupPhase, scripts in $out/bin are wrapped, and the wrapping   script walks all propagatedBuildInputs when collecting PATH and PYTHONPATH.
I also added a test that checks that outputs don't depend on poetry/compile time dependencies. It fails with the following error on master:
```
output '/nix/store/dxxkcgkl4qfypf97jcw96lgba671hqmb-closure-size-1.0.0' is not allowed to refer to …
```
> Reduce closure size of packages built with poetry2nix

- default.nix
- lib.nix
- overrides.nix
- tests/env/default.nix
Pep508 markers alone are not always enough, see #50
This sadly introduces a minor breakage in `mkPoetryEnv` (you now need to pass `pyproject` to `mkPoetryEnv` as well).
cc @Infinisil @andir @gilligan
> Add support for python version constraints from pyproject.toml

- default.nix
This function is a useful building block when the Python packages
generated are used for another purpose.
> Expose mkPoetryPackages

- default.nix
- tests/git-deps-pinned/default.nix
- tests/override-support/default.nix
- tests/prefer-wheel/default.nix
This adds the convenience functions withDefaults and
withoutDefaults which simply wrap the provided argument in a list
either with or without the default poetry overrides.
Tests have also been adapted to make use of `withDefaults` where
appropriate.
> Provide withDefaults and withoutDefaults

- default.nix
The `meta` attribute is only relevant for `mkPoetryApplication`
and can safely be dropped elsewhere.
> Drop `meta` attribute for mkPoetryPackages/mkPoetryEnv

- overrides.nix
Needed these to work. The `versioning` override for fancycompleter took a while to figure out.
I'm not entirely sure how to test these, but I can say that these overrides work in the project I'm working on.
This PR is sponsored by [Niteo](https://niteo.co/) :sparkles:
> Add overrides for fancycompleter and pylint

- overrides.nix
Instead of patching around in setup.py which isn't very reliable at
all add pytest-runner to propagatedBuildInputs where necessary and
set `doCheck=false`.
> Add pytest-runner where needed

- overrides.nix
If specified in `poetry.lock` we'll use the version from there otherwise we'll fall back to the nixpkgs version.
Also we don't want to introduce a runtime dependency on `pytest-runner` so don't propagate it.
> Use canonical pytest-runner name

- overrides.nix
The `configparser` package uses `setuptools[toml]` and thus needs `toml` to work.
> Add override for configparser

- overrides.nix
`python-jose` lists `pytest-runner` in its `setup_requires` even though it is not required for setup. The package fthus ailed to build.
> overrides: add python-jose

- default.nix
- hooks/default.nix
- hooks/pip-build-hook.sh
- hooks/pyproject-without-path.py
- mk-poetry-dep.nix
We should never have to use `format = "setuptools"` since pip can
_also_ handle setuptools packages.
This uses a custom pipBuildHook that removes pyproject.toml in case
there is also a setup.py in the same sources.
> Automatically build most packages without passing format param

- .github/workflows/ci.yml
It looked to me like there was no CI for pull requests, so I thought I'd share what a simple Actions config would look like. I personally like having the pull requests marked up automatically with build/check results.
At 30 minutes of runtime, it's pretty slow, I guess due to lack of local caching on the ephemeral build machines - probably the existing gitlab CI runs on a long-lived host - but it could still be useful, and cachix integration would be very easy. It would also be quite easy to enable builds on MacOS using this method: see the commented-out line.
> Add simple github actions checks

- pep425.nix
When no matching wheels are found, builtins.head causes this to fail with a very low-level error. Better to return an empty list and trigger the assertion in the code which calls this.
(I tried using `addErrorContext`, but it didn't seem to make the resulting error clearer.)
I also found that I can't run this test on MacOS, since the only `preferWheel` package in the overrides set (and hence the one used by the `prefer-wheel` test) does not have any MacOS wheels. Not sure how to find a legitimate example that the test could use instead, but I guess even an artificial one could work, ie. use a local override that would not normally be necessary, but which would set `preferWheel` and allow for success on all Nix platforms.
> Avoid calling builtins.head on potentially-empty list of matching wheels

- overrides.nix
This one is interesting, because `cppy` isn't in the `nixpkgs` set of python packages, so this override will only work if `cppy` is also in the poetry env that is being constructed.
> Add override for kiwisolver, which has cppy in setup_depends

- default.nix
- mk-poetry-dep.nix
- tests/default.nix
- tests/prefer-wheels/default.nix
- tests/prefer-wheels/poetry.lock
- tests/prefer-wheels/pyproject.toml
I pass some globalPreferWheels parameter to enable global wheels preference during installations.
It "works well" but for some reason, the test I added on TensorFlow fails due to some wheels URL returning 404, suggesting either a bug in PyPI or in `fetchFromPyPI`, I tried to poke around over IRC on #python but I'm not sure I'll have a proper answer.
Otherwise all tests except this one are passing.
Let me know your thoughts @adisbladis
> Enable global preference for wheels for top-level functions

- fetch-wheel.sh
- lib.nix
- overrides.nix
- tests/prefer-wheel/default.nix
- tests/prefer-wheels/default.nix
- tests/prefer-wheels/poetry.lock
- tests/prefer-wheels/pyproject.toml
Due to the way PyPI routes its wheels (security reasons apparently), it's impossible to guess the URL, without calling the PyPI API.
For posterity, why `/${kind}/` cannot work is due to this: https://gist.github.com/di/93019b51582899c294cfd76ee2d0a4a3 (list of all python versions in warehouse).
The way this PR attempts to solve it is to call the API and just replace `fetchurl` which is anyway also a fixed-output derivation.
> Fixed output derivation for wheels fetching

- overrides.nix
Without this, the wrapped isort binary cannot import setuptools.
Upstream, this will eventually be fixed when the code containing this line gets released:
https://github.com/timothycrosley/isort/blob/3e09facb2311f5b5b8bff8da90f4992e57f4bc9e/isort/main.py#L19
> Add override for isort to cover missing dependency on setuptools

- default.nix
- tests/default.nix
- tests/dependency-environment/default.nix
- tests/dependency-environment/poetry.lock
- tests/dependency-environment/pyproject.toml
- tests/dependency-environment/trivial.py
A combination of `mkPoetryApplication` and `mkPoetryEnv`: An environment with a python interpreter, all dependencies and the application built from pyproject.toml as well. In addition, all binaries know about the python modules of the application. This is useful if your application doesn't have a binary on its own, but relies on dependencies binaries to call its modules.
A test case might be a good idea, but I can say that this works very well with the project I've been testing this with locally.
Ping @adisbladis @energizah
Edit: This PR is newly sponsored by [Niteo](https://niteo.co/)
> Introduce `dependencyEnv` passthru to `mkPoetryApplication`

- README.md
- default.nix
- tests/default.nix
- tests/editable/default.nix
- tests/editable/poetry.lock
- tests/editable/pyproject.toml
- tests/editable/src/trivial/__main__.py
This introduces a new parameter to `mkPoetryEnv` which can be used to specify sources for additional python packages that should be available in the resulting environment, loading directly from the mutable source directory. This allows you to call binaries that need to load python modules (like `python -m` or `gunicorn`) for development.
This `editablePackageSources` parameter *could* be read from the [packages](https://python-poetry.org/docs/pyproject/#packages) entry in `pyproject.toml` (or inferred if it doesn't exist), and that's what `poetry install` does, but this would be rather complex to implement correctly, so passing it manually seems to make more sense to me.
The implementation of this works the same way as `poetry install` works: `.pth` files (somewhat documented …
> Introduce `editablePackageSources` to `mkPoetryEnv`

- overrides.nix
Note that imagecodecs override depends on https://github.com/NixOS/nixpkgs/pull/87205.
Also, should such large overrides go into this single file? I could see this getting out of hand quickly as it somewhat duplicates nixpkgs for complicated packages...
> add override for panel, imagecodecs

- default.nix
When a dependency itself has a git dependency the metadata to infer `ref` is not available in `pyproject.toml` and we have to fall back to `HEAD`.
> Fix nested git dependencies

- default.nix
- editable.nix
- tests/default.nix
- tests/editable-egg/default.nix
- tests/editable-egg/paste.ini
- tests/editable-egg/poetry.lock
- tests/editable-egg/pyproject.toml
- tests/editable-egg/src/trivial/__init__.py
In https://github.com/nix-community/poetry2nix/pull/101, `editablePackageSources` was introduced, but later [I discovered](https://github.com/nix-community/poetry2nix/pull/101#issuecomment-629870767) that this doesn't work for [`pkg_resources.require()`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-workingset-methods), which needs an installed egg to find the package.
With this change, this is fixed by making `mkPoetryEnv` install a very basic static egg.
In the first commit, a failing test is added, showcasing what didn't work previously, whereas the second commit makes it work.
This PR is sponsored by [Niteo](https://niteo.co/)
> Editable eggs

- overrides.nix
`pygame` could not build because of missing dependencies. The code is mostly taken from `nixpkgs`
> overrides: add pygame

- overrides.nix
Since the nixpkgs change https://github.com/NixOS/nixpkgs/commit/f149c7030a7#diff-b7d8c4fa8c1a2ad2832a889247b62e3bL3, `arrow-cpp` package expects an argument named `python3` instead of just `python`. This commit adds a compatibility fix so that the package can also be used with a newer nixpkgs.
> Make pyarrow override compatible with newer nixpkgs

- .github/workflows/ci.yml
- default.nix
- tests/eggs/default.nix
- tests/manylinux/default.nix
- tests/prefer-wheel/default.nix
- tests/prefer-wheels/default.nix
Fixes #126, was an oversight in https://github.com/nix-community/poetry2nix/pull/87
Note that moduleName is being applied to define the python pkgs overlay in https://github.com/nix-community/poetry2nix/blob/e7c69a288c10e4d97816fdabda5ae3f38e21914e/default.nix#L113, so it's also necessary when accessing the attributes
Ping @adisbladis @domenkozar @suryasr007
> Fix moduleName not being applied for accessing python pkgs set

- default.nix
- mk-poetry-dep.nix
- pkgs/poetry/default.nix
Currently Poetry does not have a notion of build-time
dependencies (setup-requires) in it's lock file.
When installing a dependency built with Poetry this has to be added
via an override which is really bad UX.
This change always adds Poetry as an interim solution until we have
resolved this in upstream Poetry.
> Always add Poetry as a build input unless bootstrapping

- lib.nix
If a project doesn't have this specified, poetry doesn't do its thing,
leading to package metadata not being detected (UNKNOWN packages)
Alternative to #135, relevant is #83 
This PR is sponsored by [Niteo](https://niteo.co/) :sparkles:
> throw an error when no build-backend is specified

- README.md
- default.nix
- tests/composable-defaults/default.nix
- tests/composable-defaults/poetry.lock
- tests/composable-defaults/pyproject.toml
- tests/default.nix
- tests/override-default-support/default.nix
Sometimes when it can be convenient to create a custom instance of `poetry2nix` with a different set of default overrides.
```nix
let
p2nix = poetry2nix.overrideScope' (self: super: {
defaultPoetryOverrides = super.defaultPoetryOverrides.extend (pyself: pysuper: {
my-custom-pkg = super.my-custom-pkg.overridePythonAttrs (oldAttrs: { });
});
});
in
p2nix.mkPoetryApplication {
}
```
> Wrap poetry2nix in a scope to make internals overridable

- overrides.nix
Adds `pytest-runner` as a build input, handling #139
> Add override for ffmpeg-python

- pep425.nix
We wouldn't match `cp38m` but only `cp38`
Closes https://github.com/nix-community/poetry2nix/issues/132
> Fix pep425 matching when modifiers are present

- overrides.nix
Closes #99 
Note there is a bug with building numpy > 1.19.0, and this depends no setuptools-scm with toml. See the following pyproject.toml
```toml
[tool.poetry]
name = "vispy_test"
authors = ["Michael Lingelbach <m.j.lbach@gmail.com>"]
python = "^3.6"
numpy = "1.19.0"
vispy = "0.6.4"
[tool.poetry.dev-dependencies]
setuptools-scm = { version = "^3.4", extras = ["toml"] }
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```
And shell.nix
```nix
with import <nixpkgs> {};
with import ../poetry2nix/overlay.nix pkgs pkgs;
let
pythonEnv = poetry2nix.mkPoetryEnv {
preferWheels = false;
};
in
mkShell {
name = "vispy_environment";
nativeBuildInputs = [
pythonEnv
];
}
```
> Add override for vispy

- overrides.nix
Override to use system (nix) freetype.
> overrides: Matplotlib 3.3.0 now downloads/builds it's own freetype by default

- overrides.nix
In previous PR I forgot about psycopg2-binary.
This is part of https://github.com/nix-community/poetry2nix/issues/146
> Add openssl for psycopg2-binary on Darwin

- overrides.nix
Took me a while to figure out to use `inherit (pkgs.pthon3.pkgs.foo) patches`.
Hopefully this helps someone: when you're able to build the package, but it fails when it's run with this kind of error:
```
raise OSError(msg)
OSError: cannot load library 'gobject-2.0': gobject-2.0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0'
```
then the above trick of inheriting `patches` might work.
> Overrides for weasyprint

- overrides.nix
requires pbr as can be seen https://github.com/mongomock/mongomock/blob/develop/setup.py
Fixes https://github.com/nix-community/poetry2nix/issues/164
> override: for mongomock

- README.md
This is a really small change to properly direct user to the section when clicking:
- overrides.withDefaults
- overrides.withoutDefaults
> fix anchor in readme

- overrides.nix
I needed these overrides to make my project build with `poetry2nix`.
I was a little confused why I needed to add the overrides for `setuptools-markdown` in e.g. `eth-hash`, because it's already present in the `nixpkgs` [package definition](https://github.com/NixOS/nixpkgs/blob/097cf628d9aa3c9a405f63f128ca6e222570e17b/pkgs/development/python-modules/eth-hash/default.nix), but maybe I'm just misunderstanding how `poetry2nix` does it's magic?
Awesome tool btw, thanks for all the work! :pray:
> Extra overrides

- overrides.nix
Overrides: jaraco-functools, portend and tempora.
Closes issue #154
> Add three overrides to make sure the pyproject.toml is not removed.

- overrides.nix
If your poetry.lock file contains a marker making a dependency optional
on a specific python version, super.zipp is null, so getting its version
will fail. There's other code handling these being null (followups on
https://github.com/nix-community/poetry2nix/issues/50), so just make
this code handle it more gracefully, too.
Co-authored-by: Florian Klink <flokli@flokli.de>
> overrides.nix: handle zipp being null gracefully

- bin/poetry2nix
- mk-poetry-dep.nix
When running nix-shell after added a git dependency, it complains invalid Git revision 'master'.
I think it should always prefer `resolved_reference` to `reference`
> fix "invalid Git revision 'master'"

- pep425.nix
- add 10_8 and 10_7 to macos version list
how to reproduce:
```
$ poetry new testpoetry
$ cd testpoetry
$ poetry add rusty-rlp
$ cat > shell.nix << EOF
with import <nixpkgs> { };
poetry2nix.mkPoetryEnv {
}
EOF
$ nix-shell
error: list index 0 is out of bounds, at /nix/store/.../nixpkgs/pkgs/development/tools/poetry2nix/poetry2nix/mk-poetry-dep.nix:71:27
(use '--show-trace' to show detailed location information)
```
> don't match macos version of rusty-rlp package

- README.md
It took me a while to figure this out, so I think it may be a useful reference for future `poetry2nix` users.
Related to and inspired by #186, #60.
> Add mkPoetryEnv shell.nix examples to README

- overrides.nix
Hi, I'd like to add overrides for two Datadog-related libs. The problem I faced was related to `datadog-lambda` library that depends on `ddtrace`. 
1. `Cython` was missing in the dependencies of `ddtrace`.
2. While testing the build on different machine (MacOS) the `darwin.IOKit` package was required.
3. The `datadog-lambda` itself didn't build with current version of setuptools. 
```toml
[tool.poetry]
name = "hello"
authors = []
python = "^3.8"
datadog-lambda = "^2.26.0"
[tool.poetry.dev-dependencies]
pytest = "^5.2"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
```bash
nix-shell
(...)
WARNING: The directory '/homeless-shelter/.cache/pip' or its parent directory is not owned or …
```
> Add overrides for datadog libraries

- README.md
- default.nix
> The editablePackage and scriptsPackage elements of the mkPoetryEnv
> function are wholly separable and really ought to be moved into the
> functionality of the mkPoetryPackages function. By doing so both will
> automatically be available in the mkPoetryApplication's dependencyEnv as
> well.
> 
> I thought the functionality that encapsulates these might further see
> potential use even outside the context of mkPoetryPackages, so I made
> them top-level functions and documented them in the README.
I wasn't sure how to add tests for these changes. Please let me know if you have any suggestions in that vein.
> Expose functions for editable & scripts packages

- overrides.nix
- tests/manylinux/default.nix
This PR is a possible solution for #232.
Closes #232
Problem:
The issue demonstrates that building a poetry environment or application
fails when using a different python version.
I trace this down to the fact that
```nix
pkgs.python3.pkgs.override { python = self.python; }
```
is not sufficient to override tools that get used to build/bootstrap packages
such as `buildPythonPackage`, `bootstrapped-pip`, and `setuptools`, all three
of which are used to build the `wheel` package.
This led to every version of wheel being built for whatever version `python3`
corresponds to for whatever version of `nixpkgs` is being used.
> overrides: fix wheel inputs to support different versions of python

- .gitignore
This PR adds `.direnv` to the repository `.gitignore` file.
> gitignore: ignore direnv

- default.nix
- lib.nix
- mk-poetry-dep.nix
- pep425.nix
- pep508.nix
- tests/default.nix
This fixes builds being completely broken after:
* https://github.com/NixOS/nixpkgs/pull/110726
* https://github.com/NixOS/nixpkgs/pull/110544
I'm not sure if this should be handled in a backwards compatible way, but if it is, I'd be happy to adjust the patch.
> Fix stdenv.platform accesses for latest nixpkgs

- overrides.nix
Fixes `packaging` build newly failing with
```
ModuleNotFoundError: No module named 'flit_core'
```
And also fixes pytest having version 0.0.0 (fixes #188), see also https://github.com/pytest-dev/pytest/issues/7891, not sure if there's a better way to fix this
> Overrides for packaging and pytest

- overrides.nix
I am using this override in my project-specific nix file, but I think it would make sense to include it in poetry2nix. The code is copy-pasted so it should work(tm).... I am not sure how to best test this PR?
> mysqlclient: Add missing native library dependency

- overrides.nix
I've had a few issues where `old.buildInputs` didn't exist for some packages, so I figured I'd make it safer once and for all.
cc @Infinisil
> safer overrides

- overrides.nix
They need toml as a build dependency, they require setuptools_scm with the toml extra.
> Add additional overrides for jaraco-functools, portend and tempora.

- README.md
- default.nix
- tests/default.nix
- tests/mk-poetry-packages/default.nix
- tests/mk-poetry-packages/poetry.lock
- tests/mk-poetry-packages/pyproject.toml
This is a fix for [#247 mkPoetryPackages no longer propagates dependencies
](https://github.com/nix-community/poetry2nix/issues/247)
@adisbladis Please take a look and check if this is stable solution!
Important facts:
- I'm doing some string operations on python.pythonVersion to produce right attribute (should look like this: `python37`, `python38`, etc.) and I have no idea if there is better option for that.
- Added tests for current and older version of Python.
- Added documentation how to run tests locally (Tests finish with "Hello, World!" and gunicorn server listening, is this expected?).
> Fix mkPoetryPackages: should return deps of deps

- overrides.nix
More info in the commit msgs.
As you can see, I kinda chickened out for `tokenizers` and used a wheel after seeing the nixpkgs override: https://github.com/NixOS/nixpkgs/blob/f5e8bdd07d1afaabf6b37afc5497b1e498b8046f/pkgs/development/python-modules/tokenizers/default.nix#L50
Is there a way to re-use the nixpkgs source build? If not, I hope the wheel is good enough!
> Provide necessary overrides to build `sentence-transformers`

- overrides.nix
I can split them up if you'd like. Either way, these are some overrides I needed today. 
I'm not sure if I use the correct phase + approach for the `django-stubs-ext` package, let me know if something should be different :smile:.
This was the error I got when I tried to install without this override:
```
error: [Errno 2] No such file or directory: '../LICENSE.txt'
----------------------------------------
ERROR: Failed building wheel for django-stubs-ext
```
> Add overrides for django, django-*, pillow, typed_ast and weasyprint packages.

- overrides.nix
python-snappy depends on snappy library.
It would be convenient if it is in the default overrides.
> Add override for python-snappy

- overrides.nix
Using poetry2nix on macOS, I just found psutil's missing dependency on Apple SDK.
It would be convenient if it is in the default overrides.
> Add override for psutil on darwin

- overrides.nix
Aiohttp-swagger3 fails to build with this minimal pyproject.toml:
```
[tool.poetry]
name = "poetry2nix"
authors = ["Your Name <you@example.com>"]
python = "^3.8"
aiohttp-swagger3 = ">=0.5.3"
[tool.poetry.dev-dependencies]
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
Seems like pytest-runner dependency is missing, so this PR adds it.
> overrides: add pytest-runner dependency for aiohttp-swagger3

- overrides.nix
Use compiled version (this supposed to offer 4x speed improvement over pure python, it's also the version that is provided through wheels).
> Use compiled version of mypy (mypyc)

- overrides.nix
Without this change a build depending on recent versions of `keyring` results in:
> ERROR: Could not find a version that satisfies the requirement importlib-metadata>=3.6 (from keyring==23.0.1) (from versions: none)
> ERROR: No matching distribution found for importlib-metadata>=3.6 (from keyring==23.0.1)
> importlib-metadata: Don't remove pyproject.toml

- overrides.nix
Every once in a while I get an error because of an override that doesn't use `or [ ]` so I figured I'd go and fix them all with a little find/replace while my code is compiling.
> safer overrides using 'or [ ]'

- mk-poetry-dep.nix
Currently I'm unable to run poetry2nix on aarch64-darwin, same as noted in this ticket https://github.com/NixOS/nix/issues/4758 I'm also getting
```
error: invalid regular expression '^.*?(egg|tar|tar.bz2|tar.gz|tar.lz|tar.lzma|tar.xz|tbz|tgz|tlz|txz|whl|zip)'
```
I believe this is related to differences in stdlib++ versions, altough this is not my area of expertise.
The question mark isn't necessary here, I hope this showcases that
```
nix-repl> builtins.match "?(egg)" "asdf"
error: invalid regular expression '?(egg)'
at «string»:1:1:
1| builtins.match "?(egg)" "asdf"
| ^
2|
nix-repl> builtins.match "^.*?(egg)" "asdf"
error: invalid regular expression '^.*?(egg)'
at «string»:1:1:
1| builtins.match "^.*?(egg)" "asdf"
| ^
2|
nix-repl> builtins.match "^.*(egg)" "asdf"
null
nix-repl> …
```
> fix regex for darwin-aarch64 compatability

- fetch-from-pypi.sh
- lib.nix
- mk-poetry-dep.nix
- tests/default.nix
- tests/markupsafe2/default.nix
- tests/markupsafe2/poetry.lock
- tests/markupsafe2/pyproject.toml
Previously we randomly encountered issues where the Pypi mirror URLs
wouldn't be correct with packages whos first character is frequently
written in upper case (e.g. SqlAlchemy, MarkupSafe, ...). The Pypi
mirrors are apparently not consistent in the naming of the file locations
which lead to random errors after package version bumps.
By falling back to the API lookup (that we already did for wheels) we
can workaround that situation.
> Always fallback to querying the Pypi API when the predicted URL 404s

- fetch_from_legacy.py
- lib.nix
- mk-poetry-dep.nix
- tests/default.nix
- tests/legacy/default.nix
- tests/legacy/poetry.lock
- tests/legacy/pyproject.toml
Some private repositories (such as Devpi) expose the legacy Pypi
API (https://warehouse.pypa.io/api-reference/legacy.html).
This commit adds a dedicated fetcher which basically queries this API
to get the URL pointing to the actual file.
Since Pypi still exposes this API, it has been possible to write a
test that uses this legacy API.
Fixes https://github.com/nix-community/poetry2nix/issues/277.
> Add support to the legacy Pypi API

- overrides.nix
> overrides: disable matplotlib lto on darwin

- overrides.nix
Since lxml requires xcrun to be present in PATH
> Adding xcodebuild as a darwin dependency for lxml

- default.nix
This is because of changes in [nixpkgs](https://github.com/NixOS/nixpkgs/pull/125477), which results in infinite recursion because of the treewide refactor. The refactor changed 
`setuptools_scm` to `setuptools-scm`, however, it also aliased `setuptools_scm`  to `setuptools-scm`. Poetry2nix then aliases `setuptools-scm` to `setuptools_scm` resulting in infinite recursion.
> Define setuptools-scm only if it is not already defined

- fetch_from_legacy.py
When the first PR has been submitted, I think the store path was already in my cache and in the CI cache so tests haven't been able to detect this error (moreover, I tried to clean my `/nix/store` but it seems i failed:/).
> Fix insecure ssl in fetch_from_legacy

- overrides.nix
This pull request fixes multiple packages:
- pygraphviz
- pyjsg
- pyshex
- pyshexc
- shexjsg
- sparqlslurper
Unfortunately, I think there are lot of packages depend on `pbr`. Is there any way to automatically detect the `pbr` requirement and apply the fix to the derivation?
> Add overrides for multiple packages

- mk-poetry-dep.nix
- pep508.nix
If a marker contains two or more instances of the substring "in" Nix regex engine in it's infitine wisdom splits only on the last one.
By changing a `*` to a `+` we can get the desired behaviour, but we do need to fall back to the previous behaviour in case the more restrictive match is not working.
> pep508: Fix `in`

- fetch_from_legacy.py
Artifactory's pypi repositories creates links from the index pages that look something like this: `../../$package-name/$version/$artifact.$ext`. This breaks since urllib does not normalize the `../` parts from the links and Artifactory does not resolve them when fetching the artifacts, leading to an unexpected 404.
This PR adds support for resolving the `../` parts of the URL.
~It also adds the `cacert` derivation into the build to allow SSL certificate verification.~
Nix is kind of new to me and I struggled really hard trying to write a sane test for this and failed so I'm posting this PR without tests and am open to write tests if someone can hint me how to set that up for testing this.
> Fix legacy relative paths including `../`

- overrides.nix
- tests/common-pkgs-2/poetry.lock
- tests/common-pkgs-2/pyproject.toml
Currently, building matplotlib fails with error:
```
ERROR: Could not find a version that satisfies the requirement certifi>=2020.06.20 (from versions: none)
```
This PR adds the failing test case, and fixes it by inserting the `certifi` dependency.
Let me know if there is a better solution.
> Fix matplotlib build

- overrides.nix
I think this is worth enabling as it is used by dask when loading data from parquet files. You get `ModuleNotFoundError: No module named 'pyarrow._dataset'` at runtime if you try without having this enabled.
> Enable dataset module in pyarrow

- default.nix
Because it would be nice to have a new release in nixpkgs (i mainly interested by a `fetch-from-legacy` fix).
(Once released, I could then submit a PR in nixpkgs.)
> Bump version to 1.18.0

- check-fmt
- check-fmt.nix
- pkgs/poetry/default.nix
This simplifies overriding Poetry with a different version.
Related issue: https://github.com/nix-community/poetry2nix/issues/345
> Expose projectDir/pyproject/poetrylock parameters in the Poetry derivation

- overrides.nix
I do not fully understand why the version specification breaks the
installation, because `poetry install` and `pip install
--requirement=<(poetry export)` both work just fine.
Closes #340.
> feat: Make virtualenv installable

- overrides.nix
This fixes llvmlite builds by using the `dev` subpackage for `llvm-config` and adds versioned LLVM support.
> overrides: fix llvmlite build and add appropriate LLVM versions

- overrides.nix
The `setup.py` generated by poetry appears to be broken for some reason.
> licensecheck override

- mk-poetry-dep.nix
- overrides.nix
The `+` symbol was used in the version string of some private packages I depend on.
It seems to be standardised as a way to concatenate extra version information for e.g. local rebuilds: https://www.python.org/dev/peps/pep-0440/#local-version-identifiers
> Enable '+' in package versions, and some overrides

- pep508.nix
- tests/default.nix
- tests/pytest-randomly/default.nix
- tests/pytest-randomly/poetry.lock
- tests/pytest-randomly/pyproject.toml
This PR is a possible fix for #379, using version comparison functions instead of comparison operators for comparing marker values.
A previously failing test is included.
Closes #379.
> python: fix marker comparison

- mk-poetry-dep.nix
- overrides.nix
This prevents infinite recursion against nixos-unstable-small as of NixOS/nixpkgs@ab126c9a62ca414a933ac19e91d27ddd68cedcd4.
> fix: prevent infinite recursion when using tomli

- overrides.nix
When building a Poetry application with `preferWheels = true` and  `shellingham` as a dependency, the override changes the format to `pyproject` but the input to derivation is a `.whl` file. Because the format now is `pyproject`, the wheel hook doesn't run and the build fails.
> fix: only change shellingham format to pyproject if format is not wheel

- pep425.nix
Wheel filenames can have the format "mediapipe-0.8.7.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl".
Currently the check is for an exact match in the platform bit, i.e. "manylinux_2_17_x86_64.manylinux2014_x86_64".
This change checks whether the platform bit contains the platform we're looking for anywhere in it.
#386
> fix: add support for wheels files w/ multiple platforms seperated by a period

- overrides.nix
Alternative to https://github.com/nix-community/poetry2nix/pull/388
Closes #375 (which seems unrelated but I can build black on latest nixpkgs unstable with this fix).
> overrides: Fix building black

- overrides.nix
This is comparable to #99/#142.
> overrides: add setuptools-scm-git-archive to jira

- overrides.nix
Override the dontPreferSetupPy attribute for cheroot, otherwise it will try to download `setuptools_scm_git_archive` and fail when `sandbox = true`.
> Override the dontPreferSetupPy attribute for cheroot

- default.nix
So `meta.position` will resolve to where the package is defined instead of pointing to Poetry2nix internals.
> Explicitly pass pos to stdenv.mkDerivation

- README.md
Resolve #186.
The current documentation shows how to include dev-dependencies in
environment *or* add external dependencies to the environment, but I
suspect in the vast majority of cases both will be desired.
> README: recommend overriding env over mkShell

- overrides.nix
I'm running into another build issue with `preferWheels = true` and `zipp==3.6.0`. Skipping the `setup.py` patch if format is wheel seems to work.
> fix(zipp): skip patching setup.py if format is wheel

- overrides.nix
- tests/default.nix
- tests/uwsgi/default.nix
- tests/uwsgi/poetry.lock
- tests/uwsgi/pyproject.toml
This adds an uwsgi override that resolved a build issue on my own project. 
I also tried adding tests, I copied the example of `pendulum`, but I was unable to run the tests locally. `nix-build --keep-going --show-trace tests/default.nix` hangs for me on this output:
```
building '/nix/store/wzm0xa83yldljcd4c27kwzl1yyhp9vxw-app-env-test.drv'...
[2021-10-04 16:41:55 +0000] [54167] [INFO] Starting gunicorn 19.10.0
[2021-10-04 16:41:55 +0000] [54167] [INFO] Listening at: unix:socket (54167)
[2021-10-04 16:41:55 +0000] [54167] [INFO] Using worker: sync
/nix/store/5vn5f6slfg1nw8q0bhapd3vgk9j7559i-python3-3.8.7/lib/python3.8/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
return io.open(fd, *args, **kwargs)
[2021-10-04 …
```
> Add uwsgi override

- overrides.nix
Many of these seem to be passing with the latest version, so it should be safe to re-enable them.
> feat: Re-enable tests

- overrides.nix
See discussion on
<https://github.com/nix-community/poetry2nix/pull/428>.
This reverts commit 0b9f3e19f43c3081a9c14cad7b2ed6f1668b7b9a.
> Revert "feat: Re-enable mypyc from version 0.910"

- overrides.nix
Without this change the build of jsonschema-4.2.1 fails with:
> ERROR: Could not find a version that satisfies the requirement importlib-resources>=1.4.0; python_version < "3.9" (from jsonschema)
> ERROR: No matching distribution found for importlib-resources>=1.4.0; python_version < "3.9"
The problem seems to be similar to #294, and the same fix seems to work.
> importlib-resources: Don't remove pyproject.toml

- fetch_from_legacy.py
The [PyPI Legacy API documentation][1] says that the distribution downloads for project can be accessed via a request
GET /simple/<project>/
but the current implementation instead makes a request
GET /simple/<project>
There exist some custom repository servers that give erroneous responses to requests without the slash, so include the slash.
[1]: https://warehouse.pypa.io/api-reference/legacy.html
> Include the trailing slash in legacy index URL

- overrides.nix
Since version 1.7.0, the Pythran transpiler is [enabled by default](https://scipy.github.io/devdocs/release.1.7.0.html#other-changes) when building `scipy`.
> overrides: scipy: fix for version >= 1.7.0

- overrides.nix
Add override for [`WTForms`](https://pypi.org/project/WTForms/):
- add `buildInputs` override for [`setup_requires=Babel`](https://github.com/wtforms/wtforms/blob/0beff0b5c29f4995ea1c573d3c1d043471b6e1c3/setup.cfg#L30)
- tested against 3.0.0
> overrides: wtforms: add

- overrides.nix
Packaging-relevant changes in matplotlib 3.5.0:
- `setup.cfg` was renamed `mplsetup.cfg` ([changelog](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#matplotlib-specific-build-options-moved-from-setup-cfg-to-mplsetup-cfg), matplotlib/matplotlib#20871)
- `setuptools_scm` is used instead of `versioneer`(matplotlib/matplotlib#18971).
Updated the override accordingly.
> overrides: matplotlib: fix for version >= 3.5.0

- overrides.nix
[`argon2-cffi`](https://pypi.org/project/argon2-cffi/) migrated to `flit` at hynek/argon2-cffi@cb0248d29ab20784ffe26d969bb43aa91fade1c2 which was integrated into the 21.2.0 release.
> overrides: argon2-cffi: fix for version >= 21.2.0

- overrides.nix
- fix: ensure that arrow-cpp isn't built twice when python3 != python
- refactor: remove _arrow-cpp from buildInputs
- build: minimize use of pkgs.arrow-cpp
`arrow-cpp` is built twice when `self.python != self.python3`, because of the override to `_arrow-cpp`, and then later use of `pkgs.arrow-cpp`. This PR moves everything to use the override.
> fix: remove double build of arrow-cpp when self.python != self.python3

- overrides.nix
Hi! Friendly upstream here. We made some change[1] that will make your `postPatch` override ineffective. This should make a backwards-compatible change to correct that. Also, I'm not a poetry user, so this is untested. I hope you can help me with that.
cc @K900
[1] https://github.com/NixOS/nixpkgs/commit/7dc44307515de130daf661814891d8844fdf701f
> overrides: matplotlib: use MPLSETUPCFG

- fetch_from_legacy.py
- lib.nix
I've been wanting this for a while, so I finally had a crack at it.
Credentials are declared in a file which is passed to poetry2nix as an argument.
I used this project to test it out: https://github.com/rskew/poetry2nix-private-pypi-demo
I haven't given a lot of thought to the design, I just wanted to draft something that works as a demo. Feedback appreciated!
> Enable private pypi repositories with credentials

- README.md
- default.nix
This is a function taking a Python package set and returning a list of extra packages to include in the environment. 
This is intended for packages deliberately not added to `pyproject.toml` that you still want to include.
An example of such a package may be `pip`.
> mkPoetryEnv: Add an extraPackages argument

- default.nix
This allows for IFD style projectDir.
Closes #435
> Don't filter sources where the projectDir is the output of a derivation

- .github/dependabot.yml
But we don't want to auto-bump tests for obvious reasons.
> Add dependabot configuration to update Poetry

- default.nix
This isn't quite done as the dependency build fails because it's missing the dependency, but at least evaluation passes.
> Create a dummy null package for the current project in case any dependencies depend on the root project

- README.md
- default.nix
This removes a lot of boilerplate from Nix code and I think that this is the expected behaviour.
~We might want to have a mechanism to _exclude_ some packages from being editable.~
~Maybe simply explicitly setting the editable path to `null` would suffice?~
This is now implemented in the second commit of this PR.
> Add path dependencies where develop=true as editable packages by default

- overrides.nix
Adds `pbr` as a propagated build input to `requests-mock`.
I'm able to successfully build a poetry2nix package with change. It doesn't look like we add tests for every override, but I'm happy to add tests as needed.
> Adds pbr to requests-mock.propagatedInputs

- pep425.nix
This is an attempt to make the wheel selection work in a more precise way on aarch64 darwin platforms. The motivating example was trying to install pytorch: https://pypi.org/project/torch/#files. The current version of poetry2nix was selecting `torch-1.10.1-cp39-none-macosx_10_9_x86_64.whl` which is incompatible with the arm infrastructure. This PR will filter out any wheels which don't match the target architecture.
Note: I am quite new to nix/poetry2nix so I may not have done this in the most idiomatic way. I also don't have a non-m1 mac to hand to double check I haven't accidentally broken things on there.
> make wheel selection more sophisticated for m1 macs

- overrides.nix
It's required by [webcam-filters](https://github.com/jashandeep-sohi/webcam-filters), I tested it [here](https://github.com/kurnevsky/nixfiles/blob/1e2a0dff9eb1477aea7563556783bd74e8cc7c99/modules/webcam-filters.nix#L22).
> overrides: fix opencv-contrib-python the same way as opencv-python

- overrides.nix
Remove `moto` override causing issue https://github.com/nix-community/poetry2nix/issues/315
The override was originally added by me in https://github.com/nix-community/poetry2nix/commit/3484e377f9e0c4a469348b3f6571f4a6edbd896c#diff-9e070d83f19cc15366efc74d8828a77e0bea1c62e55afd83c8e19f17d907a7fdR582
> overrides: remove problematic moto override

- overrides.nix
- tests/default.nix
- tests/fetched-projectdir/default.nix
This fixes the build for `fastapi` which requires `flit` as a build input and adds a test for IFD projectDir which was added in f3f70444b7ec8dfbb1867d8fa99c6cff1fb7f139 without a test case.
cc @manveru
> tests: Add test for IFD projectDir

- fetch_from_legacy.py
This fixes a regression introduced by f7ab15e390653988bcf941790a411cabfd8527b4.
In case of a devpi repository,
- the index url looks like
https://devpi.company/company/dev/+simple/python-package
- the package relative URL looks like
/../../+f/d00/a3edd114f3e81/package.tar.gz#sha256=d00a3edd114f3e813e0e22e07513361b00d925fb67057a3452a897c8623f73f6
- the URL to download the package is
https://devpi.company/company/dev/+f/d00/a3edd114f3e81/package.tar.gz#sha256=d00a3edd114f3e813e0e22e07513361b00d925fb67057a3452a897c8623f73f6
With the commit f7ab15e390653988bcf941790a411cabfd8527b4, the URL to
download the package was
https://devpi.company/+f/d00/a3edd114f3e81/package.tar.gz#sha256=d00a3edd114f3e813e0e22e07513361b00d925fb67057a3452a897c8623f73f6
which doesn't exist.
@rskew since you authored …
> The package URL is relative to the index URL

- overrides.nix
scikit-image has a `requirements/build.txt` that does not get picked up automatically. This adds the listed requirements manually to `nativeBuildInputs`. I don't know if that's the best approach, but it builds.
> overrides: add scikit-image

- templates/app/flake.nix
It seems this is an anti-pattern, according to https://nix.dev/anti-patterns/language#rec-expression.
So, I suggest to remove it from there. Better not ship anti-patterns on templates, isn't it?
> Remove rec from template

- overrides.nix
pyrfr requires `swig` to build
> overrides.pyrfr: add override

- default.nix
- overrides.nix
This is a more principled fix to https://github.com/nix-community/poetry2nix/pull/510 that will hopefully prevent this entire class of errors.
> Add overlay that disables checks for packages inherited from nixpkgs

- mk-poetry-dep.nix
This is a revival of #424 since it seems like upstream has zero interest in fixing this issue.
>  fetchGit: work-around bug in Nix 2.4

- mk-poetry-dep.nix
- overrides.nix
This PR removes a dependency on `poetry` that gets put into most dependencies
as a `buildInputs` if poetry2nix isn't bootstrapping, which if I'm reading the
code correctly is nearly everywhere (`__isBootstrap` is `false` by default).
This is a problem when building using `crossSystem` (I'm trying to
build a Docker image using musl) because any dependency that overlapped with
`poetry`'s dependencies would cause both the build *and* host platform versions
of poetry's deps to be installed, causing a conflict during build.
It also appears that this bootstrap dependency is not necessary, at least
according to the current test suite. The only package that needed modification
was `pendulum`.
> build: remove bootstrap dependency on poetry

- hooks/pip-build-hook.sh
- nix/sources.json
- overrides.nix
- tests/default.nix
- tests/file-src-deps-level2/default.nix
- tests/file-src-deps/default.nix
It seems like this bandaid to avoid some build-system related overrides causes more problems than it fixes.
Let's just deal with reality up-front and hope that https://github.com/python-poetry/poetry/issues/2789 will be fixed at some point.
Additionally this results in _much_ better error messages since you will be told exactly what input is missing.
With the faulty version detection you are simply told "the version is none".
> Remove dontPreferSetupPy & don't remove pyproject.toml

- overrides/build-systems.json
Added build system for:
- aws-error-utils
- fastapi-restful
- prometheus-fastapi-instrumentator
- fhconfparser
- licensecheck
- metprint
- requirements-parser
This also fixes https://github.com/nix-community/poetry2nix/issues/532
> Added build-system for unknown packages

- overrides/default.nix
Checking the tarballs on pypi, it seems this override is only needed for 2.0.19.x release series. Applying it to other releases causes the build to fail.
> overrides.uwsgi: only change sourceRoot for 2.0.19.x

- overrides/default.nix
So last time we disabled compilation, because it was broken since release of 0.900: https://github.com/nix-community/poetry2nix/issues/323
Looks like things blocking it got resolved and it could be enabled once again. This will increase build time, but then produce a much faster version of mypy.
Compilation could be disabled once again by overriding:
```
MYPY_USE_MYPYC=0
```
or time spent could be reduced by:
```
MYPYC_OPT_LEVEL=<value between 0 and 3>
```
> Compile mypy once again

- hooks/default.nix
- hooks/fixup-hook.sh
This is a fairly common packaging mistake that it's better that we solve in a hook than in one-by-one in overrides.
> Add hook to remove normal files from site-packages

- overrides/default.nix
Also add an importscheck for the "magic" module. Without this override,
an error such as this occurs:
>   ImportError: failed to find libmagic.  Check your installation
> overrides.python-magic: patch libmagic path

- overrides/default.nix
https://pypi.org/project/pikepdf/
> overrides.pikepdf: add qpdf and pybind11 buildInputs

- overrides/default.nix
https://pypi.org/project/pymediainfo/
This code is taken from nixpkgs https://github.com/nagy/nixpkgs/blob/6f02ba937a5df77d0a7ae5b3748a55599a96c1df/pkgs/development/python-modules/pymediainfo/default.nix#L15-L23
> overrides.pymediainfo: patch libmediainfo paths

- overrides/build-systems.json
- chore(build-systems/mkdocs-autorefs): add pdm-pep517 to nativeBuildInputs
- build-systems: add pytest-profiling
> chore(build-systems): add pytest-profiling

- overrides/build-systems.json
It looks like `mkdocs-autorefs` moved from `poetry` to `pdm` recently.
I'm not sure if including both `poetry` and `pdm-pep517` in `nativeBuildInputs`
is a great idea, but I'm also not sure how to handle build systems that differ
by version.
@adisbladis is there a way to do that in `poetry2nix` currently?
> chore(build-systems/mkdocs-autorefs): add pdm-pep517 to nativeBuildInputs

- overrides/default.nix
Fixes https://github.com/nix-community/poetry2nix/issues/561
This PR includes the rebased version of change under https://github.com/python/mypy/pull/11143
> Fix mypy 0.940+

- overrides/default.nix
MarkDown file doesn't exist in source, yet is sourced, so let's place it
there.
> overrides.ccxt: patch path to README

- lib.nix
- overrides/default.nix
- pep425.nix
- tests/default.nix
- tests/pep600/default.nix
- tests/pep600/poetry.lock
- tests/pep600/pyproject.toml
This adds support for [PEP 600](https://peps.python.org/pep-0600/), which covers a new tagging system for manylinux. Merging this would close #449.
I added a test that installs [open3d](https://pypi.org/project/open3d/) in `pep600.nix`.
While implementing this I also did the following to get this test to pass:
- did a minor cleanup of `lib.strings` references in `pep425.nix`,
- Added support for multiple (dot-separated) platform tags:
- (e.g. `numpy-1.22.3-pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`)
- Fixed a minor bug where the build system was added to `nativeBuildInputs` in overrides.nix for wheels.
- Added some overrides for `open3d` and `jupyter-packaging`.
Since this has turned into quite a lot of stuff, I suggest reviewing this PR per commit.
Since this is my …
> Add PEP 600 (new manylinux) support

- lib.nix
Since I'm not allowed to force push #585 I'm opening this PR for a CI run before merge.
Closes #585
> fix: avoid infinite recursion while searching for path #585

- default.nix
- tests/default.nix
- tests/path-deps-develop/default.nix
- tests/path-deps-develop/dep1/setup.py
- tests/path-deps-develop/poetry.lock
- tests/path-deps-develop/pyproject.toml
See these docs: https://github.com/nix-community/poetry2nix/blob/99c79568352799af09edaeefc858d337e6d9c56f/README.md?plain=1#L86
They say that any dependency passed as `null` is forced to be non editable, even if it is marked as `develop = true` in `pyproject.toml`.
However, this was not being the case.
Added a test to prove the need for the fix.
@moduon MT-83
> fix: support nullified editablePackageSources in mkPoetryEnv

- overrides/default.nix
When copying & pasting accidentally I missed 2 characters from the hash of 3.6.7. This is also converting to new hash style, so mistake like that would be more visible.
> Used incorrect hash for orjson 3.6.7

- overrides/default.nix
See #594
This solved my issue locally.  I'm not sure how to check for this in `tests/`, Since it's a runtime error not picked up at `mkPoetryApplication`.
`postPatch` phase is chosen only because that's what's in NixPkgs.
Thanks to @takeda for their guidance!
> make soundfile find libsndfile at runtime

- overrides/default.nix
https://github.com/platformdirs/platformdirs/pull/75 was released yesterday.
> fix: add hatchling for platformdirs

- tests/default.nix
- tests/eggs/default.nix
We don't want to accidentally end up with aliases in the code base
that then breaks nixpkgs when it's eventually incorporated.
> tests: Set `allowAliases = false`

- overrides/default.nix
With this I can build Synapse `v1.58.0` which has just migrated to Poetry: https://matrix.org/blog/2022/05/05/synapse-1-58-released.
> overrides.psycopg2cffi: Add override

- pep425.nix
Some wheels have build tag with more than one digit like, for instance, Openvino **"openvino-2022.1.0-7019-cp36-cp36m-manylinux_2_27_x86_64.whl"**, where the build tag is 7019.
> Some wheels have build tag with more than one digit

- hooks/default.nix
- hooks/pyproject-without-special-deps.py
- hooks/remove-special-dependencies.sh
- tests/default.nix
This is needed because Scipy parses pyproject.toml by hand, under
the assumption of one dependency per line.
This closes #613.
> Don't change format of pyproject.toml when removing special dependencies

- overrides/default.nix
- overrides/shapely-rewrite.py
Inheriting patches from nixpkgs is brittle and just a shortcut.
Instead patch the AST of the file that looks up the library paths which should be much less brittle over time.
Fixes #628.
> overrides.shapely: Remove patch

- overrides/default.nix
The patch is adapted from nixpkgs:
https://github.com/NixOS/nixpkgs/blob/77aff919e15c8e2e9a335bf7028720750d0381fd/pkgs/development/python-modules/magic/default.nix#L12
> overrides.file-magic: patch it to find libmagic

- overrides/default.nix
- tests/default.nix
- tests/shapely/default.nix
- tests/shapely/poetry.lock
- tests/shapely/pyproject.toml
- shapely: add test
- shapely: use python3Minimal to ensure ast.unparse exists
> shapely: use correct python version for ast.unparse when using python3.8

- overrides/default.nix
The old patch URL did not apply cleanly for 0.960 and 0.961.
Looks like the PR was eventually merged so hopefully these might be the last versions needing a patch.
Fixes https://github.com/nix-community/poetry2nix/issues/656
> Updated patch for mypy 0.960+

- overrides/default.nix
It's curerntly set to a specific version in setup.py, but since it's missing from
dependency metadata it fails at build time.
> overrides.secp256k1: Loosen up pytest-runner version constraint

- overrides/build-systems.json
- overrides/default.nix
jsonschema switched to the hatchling backend starting with [version 4.6.0](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.6.0).
> build-systems: optional build system objects with version information

- overrides/build-systems.json
`sane-python` uses `poetry-core` as the build-system.
> build-systems: add sane-python

- overrides/build-systems.json
After #663 `jsonschema` still did not build for me:
```
Processing /build/jsonschema-4.6.0
Running command Preparing metadata (pyproject.toml)
Traceback (most recent call last):
File "/nix/store/gq3ws3843pr18gsfafnmc6n2wv5a85sv-python3.9-pip-22.0.4/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
hook = backend.prepare_metadata_for_build_wheel
AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_wheel'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/nix/store/h2lp7lnbrqx0zb5qk2krh62g5v9ifa8d-python3.9-hatchling-0.25.0/lib/python3.9/site-packages/hatchling/metadata/core.py", line 1197, in cached
self._cached = …
```
> build-systems: add hatch-vcs for jsonschema >= 4.6.0

- mk-poetry-dep.nix
Fixes infinite recursion with recent setuptools-scm.
CC #648 (but not a proper fix)
> fix: also ignore typing-extensions when resolving dependencies

- overrides/default.nix
See https://github.com/nix-community/poetry2nix/pull/679#issuecomment-1175235244 for why I have removed 37.0.4
Also see https://github.com/openssl/openssl/commit/6677e4519d09ce49e83217fa1f685e592d1648f3 for the actual regression that actually brings down the whole application when ran an a sufficiently new CPU.
Also improved the error message for unknown versions to make updating cryptography easier in the future.
> Cryptography 37.0.4

- pkgs/poetry/poetry.lock
- pkgs/poetry/pyproject.toml
- pkgs/poetry/src.json
Lockfile regenerated manually because 1.1.13 generates broken lockfiles.
> pkgs/poetry: update to 1.1.14

- overrides/build-systems.json
`cfel-pylint-checkers` is a package I maintain, so if there are any questions, I can change things.
> cfel-pylint-checkers: add poetry-core to build-systems.json

- overrides/default.nix
[Changelog](https://mypy-lang.blogspot.com/2022/07/mypy-0971-released.html) with the included pull request https://github.com/python/mypy/pull/11143 in mypy.
> Don't apply the mypy patches after 0.971, the changes are released.

- overrides/build-systems.json
[griffe](https://github.com/mkdocstrings/griffe) uses pdm-pep517 for build system.
> build-systems: use pdm-pep517 for griffe

- overrides/build-systems.json
jupyterlab-server requires hatchling for build system.
> build-systems: use hatchling for jupyterlab-server

- overrides/build-systems.json
[`pkgutil-resolve-name`](https://github.com/graingert/pkgutil-resolve-name) uses `flit-core` for build system.
> build-systems: use flit-core for pkgutil-resolve-name

- overrides/build-systems.json
These two jupyter server/lab extensions require `jupyter-packaging` for build.
- [jupyter_server_mathjax][1]
- [jupyterlab-git][2]
[1]: https://github.com/jupyter-server/jupyter_server_mathjax
[2]: https://github.com/jupyterlab/jupyterlab-git
> build-systems(jupyter-server-mathjax, jupyterlab-git): use jupyter-packaging

- overrides/build-systems.json
The `jsonschema` module got yet another build dependency in the 4.11.0 release — `hatch-fancy-pypi-readme`:
https://github.com/python-jsonschema/jsonschema/pull/983/commits/a9b5bb2a7cd02bee23b0d2ea33cdf395854de4df
> build-systems: use hatch-fancy-pypi-readme for jsonschema >= 4.11.0

- overrides/build-systems.json
The `dotty-dict` module switched to the `poetry-core` build system since release 1.3.1:
https://github.com/pawelzny/dotty_dict/commit/a3f4b3f52d3bbad56aeccb0f4bd2c4bab14d451a#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711
(`pyproject.toml` in that commit still says “1.3.0”, but that's actually a post-1.3.0 commit)
> build-systems: use poetry-core for dotty-dict >= 1.3.1

- hooks/pyproject-without-special-deps.py
- overrides/default.nix
`mkPoetryApplication` fails when a editable path dependency exists in `pyproject.toml`, similar to #284 
This PR fix the problem by removing `develop` attributes in path / git dependencies in hooks.
> Fix build failure when pyproject.toml contains editable path dependencies

- default.nix
- lib.nix
Poetry replaces underscores with hyphens in module names.
This leads to the problem that things like
```
hiro_models = { git = "git@github.com:vale981/two_qubit_model.git", branch="online_calculation" }
```
don't work, because the `sourceSpec` is empty in
```
if isGit then
(
builtins.fetchGit ({
inherit (source) url;
rev = source.resolved_reference or source.reference;
ref = sourceSpec.branch or (if sourceSpec ? tag then "refs/tags/${sourceSpec.tag}" else "HEAD");
} // (
let
nixVersion = builtins.substring 0 3 builtins.nixVersion;
in
lib.optionalAttrs ((sourceSpec ? rev) && (lib.versionAtLeast nixVersion "2.4")) {
allRefs = true;
}
))
)
```
The poetry lock entry for this looks like
```
[[package]]
name = "hiro-models"
version = "1.2.3"
description = "Operators …
```
> fix poetry replacing underscores with hyphens

- hooks/default.nix
Prevents:
```
python3> error: collision between `/nix/store/l2ys5d4p144krknjy4iismcyppgfnwq8-python3.9-rsa-4.8/lib/python3.9/site-packages/LICENSE' and `/nix/store/lym0ljzxd0wc7m6m6pvpc4i6yv4jrig2-python3.9-types-s3transfer-0.6.0.post4/lib/python3.9/site-packages/LICENSE'
error: builder for '/nix/store/k99pmcqj8c5sbrpgi2kx0x7zv3cisgwf-python3-3.9.13-env.drv' failed with exit code 25;
last 1 log lines:
> error: collision between `/nix/store/l2ys5d4p144krknjy4iismcyppgfnwq8-python3.9-rsa-4.8/lib/python3.9/site-packages/LICENSE' and `/nix/store/lym0ljzxd0wc7m6m6pvpc4i6yv4jrig2-python3.9-types-s3transfer-0.6.0.post4/lib/python3.9/site-packages/LICENSE'
For full logs, run 'nix log /nix/store/k99pmcqj8c5sbrpgi2kx0x7zv3cisgwf-python3-3.9.13-env.drv'.
error: 1 dependencies of derivation …
```
> site-packages fixup hook: Also remove LICENSE files

- overrides/default.nix
Ran into this issue while building `zigpy`.
```
trace: warning: Unknown cryptography version: '38.0.1'. Please update getCargoHash.
[1/12/65 built, 36 copied (1502.3/1502.5 MiB), 241.3 MiB DL] building cryptography-38.0.1-vendor.tar.gz (buil
error: hash mismatch in fixed-output derivation '/nix/store/yj3wci62jqhkv83wi1d53awpcsb5wjhb-cryptography-38.0.1-vendor.tar.gz.drv':
specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
got:    sha256-o8l13fnfEUvUdDasq3LxSPArozRHKVsZfQg9DNR6M6Q=
error: 1 dependencies of derivation '/nix/store/09l5szr64c7hrngc5kyg2klhw0jcy538-python3.10-cryptography-38.0.1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/68hqsyh7nhdhzkh7lawl20jnvlcfzyk3-python3.10-zigpy-0.50.3.drv' failed to build
```
> Overrides: cryptography 38.0.1

- overrides/build-systems.json
Starting with version 0.84.0 fastapi uses hatchling instead of flit: https://github.com/tiangolo/fastapi/commit/4267bd1f4f716244a8087e5aa0e68c1de629cfa9
> FastAPI hatchling

- overrides/build-systems.json
- overrides/default.nix
Overrides added:
1) suds - For some reason, suds deploy the same package under two different names, where the name is configured at build time via environment variable. https://github.com/suds-community/suds/blob/a616d96b070ca119a532ff395d4a2a2ba42b257c/setup.py#L648
2) mdit-py-plugins - https://github.com/executablebooks/mdit-py-plugins/blob/c35bf143fb45e8572a1488cd78a96a1bbbb92bfb/pyproject.toml#L2
> Overrides: add suds, mdit-py-plugins

- overrides/build-systems.json
- overrides/default.nix
These are part of the dependency footprint of Stable Diffusion, although in fact in real life I ended up overriding `opencv-python-headless` to just point to `opencv-python` (because in the particular case of Stable Diffusion, both packages are in the footprint and they conflict).
I've tested these build on aarch64-darwin, although I haven't yet got the end-to-end test (namely "run SD") because of at least two unrelated problems (#721, and my inability to get the libjpeg dylib into the `torchvision` search path).
> Overrides: ftfy, shortuuid, contourpy, omegaconf, opencv-python-headless

- .gitignore
- fetch_from_legacy.py
Fixes #718.
I don't know how best to test this. It looks like the tests we currently have are all integration tests (`tests/legacy/`), and the Torch repo (which is the one I found that displays this behaviour) is fast-moving; the tests will break within about a month if I test against Torch. I have tested this locally against the Torch repo, though.
> Allow legacy package indices to return absolute paths

- overrides/default.nix
Older versions of `cryptography` currently can't be used, since `openssl_3` was made the default `openssl` package in nixpkgs, which they're not compatible with. Choose an appropriate version of OpenSSL, based on what the official wheel is built against according to https://cryptography.io/en/latest/changelog/.
> overrides: Choose the correct OpenSSL version for cryptography

- templates/app/flake.nix
I think this makes the new template more useful, because a user can `nix flake init` with it in an existing project and then `nix develop` to get an environment with poetry already installed to start packaging their app.
> Adds a devshell to template which includes poetry

- templates/app/flake.nix
Previously, tracked nixpkgs/main which almost guarantees lots of cache misses and compiling from source.
> Makes template track nixos-unstable

- overrides/default.nix
- tests/bcrypt/default.nix
- tests/bcrypt/poetry.lock
- tests/bcrypt/pyproject.toml
- tests/default.nix
PR to address https://github.com/nix-community/poetry2nix/issues/733.
As mentioned in the issue, I've copied the approach taken for the `cryptography` library: https://github.com/nix-community/poetry2nix/blob/9fee29254a0ea0e6a4432cf36a71a2b7317c9767/overrides/default.nix#L321-L364
Tests successfully build version 4 locally on darwin. I wasn't sure how to calculate the shasum, so I put a random one, tried to build it, then pasted the one calculated by the build process.
> Add support for building bcrypt 4 (rust)

- default.nix
- editable.nix
- known-build-systems.json
- lib.nix
- mk-poetry-dep.nix
- overrides/build-systems.json
- overrides/default.nix
- tests/default.nix
- tests/extras/poetry.lock
- tests/extras/pyproject.toml
- tests/setuptools/default.nix
- tests/setuptools/poetry.lock
- tests/setuptools/pyproject.toml
- tools/find-build-systems.py
> Trying to fix the setuptools fallout

- overrides/default.nix
- tests/default.nix
- tests/watchfiles/default.nix
- tests/watchfiles/poetry.lock
- tests/watchfiles/pyproject.toml
Resolves: #731 
Currently, `watchfiles` does not include `Cargo.lock` in the tarball released on PyPi. However, it will be fixed with the next release. For now, I've added an override with sources from GitHub down to release`0.10`, except for `0.16.0`. It won't build due to missing PyPi sources (it was fixed in `0.16.1`):
```shell
error: Missing suitable source/wheel file entry for watchfiles
```
All the remaining releases I've successfully built with:
poetry2nix: [`b470167`](https://github.com/nix-community/poetry2nix/commit/b470167f368852532a4e0fae5052b172966bf1da)
nixpkgs: [22.05](https://github.com/NixOS/nixpkgs/archive/b542cc75fa03a3a29350d4c3b69739e946268a93.tar.gz)
python: 3.9
Have a good one!
> Overrides: add watchfiles

- default.nix
- tests/default.nix
- tests/test-group/default.nix
- tests/test-group/poetry.lock
- tests/test-group/pyproject.toml
- tests/test-group/test_group/test_simple.py
This PR adds the ability to specify a `checkGroups` field that will include
poetry 1.2 dependency groups in `checkInputs`. For backwards compatibility
`checkGroups` defaults to `[ "dev" ]`.
> add support for specifying dependency groups that are checkPhase-only

- overrides/default.nix
- pep425.nix
Version specifiers should be interpreted as lower bounds for required interpreter version.
A side-effect of this change is that `cryptography` can be installed from a wheel.
Fixes #254
> PEP 425 compatibility improvements

- overrides/default.nix
Override fixes for `ansible < 5.0.0`, `open3d` and `pyrealsense2`.
> Various overrides fixes

- overrides/default.nix
[nixpkgs is dropping gdal_2](https://github.com/NixOS/nixpkgs/pull/195213), and fiona has supported this since 1.8.9 (released 2019-10-21).
See also: https://github.com/NixOS/nixpkgs/pull/195316
> fiona: switch from gdal_2 to gdal

- default.nix
Most notably this version moves files from metadata.files to being per package entry in the lock.
> Add forwards compatibility with Poetry lock version 2.0

- overrides/build-systems.json
This includes `setuptools` when building `django-cockroachdb` and `psycopg2-binary`.
> Add `setuptools` to additional package builds

- overrides/build-systems.json
Adds setuptools as build system for faust-streaming, mode-streaming, python-schema-registry-client, and svix-ksuid. All packages I've added these overrides to recently in my own builds
> build-systems: add setuptools for various packages

- default.nix
- tests/default.nix
- tests/git-deps-1_2_0/default.nix
- tests/git-deps-1_2_0/poetry.lock
- tests/git-deps-1_2_0/pyproject.toml
This fixes an issue I was having when specifying a dev dependency via git. Hopefully this is the right way. The test I have added passed once I did the fix.
The issue was:
```
error: attempt to call something which is not a function but a set
at /nix/store/fnmpdpj4acacb9ij2sskjj5rdpkp618i-source/default.nix:205:31:
204|                           or (normalizePackageSet pyProject.tool.poetry.dev-dependencies or { }).${normalizedName}
205|                           or (normalizePackageSet pyProject.tool.poetry.group.dev.dependencies { }).${normalizedName} # Poetry 1.2.0+
|                               ^
206|                           or { }
```
> fix: eval error on poetry 1.2 when a dev dependency is from git

- overrides/build-systems.json
Without this change, my project that depends on these two packages would only work with `preferWheels = true`.
Would be happy to push these deps upstream as well (or instead), but I'm not really sure how that would work— the sources are here:
- https://github.com/viraptor/arpy/blob/master/setup.py
- https://github.com/memory/python-dpkg/blob/master/pyproject.toml
Honestly it's kind of surprising that `setuptools` especially needs to be explicitly stated as a dep.
> Add overrides for arpy, pydpkg

- overrides/build-systems.json
- overrides/default.nix
This adds the direct override for `tensorflow-macos`, and adds `setuptools` as `buildInputs` for three of its dependencies.
With this change, the only user requirement to get `tensorflow-macos` working is a workaround for #750.
I was unsure of a few things.
1.  This works with `buildInputs`, so I've used that (rather than, say `propagatedBuildInputs`) — I presume this is the correct choice?
2.  The direct overrides for `tensorflow-macos` should probably be the same as those for `tensorflow` itself, but I don't know whether that is desirable.
If it is not, then the final commit can be dropped.
(If it is then the latter two commits should probably be merged.)
I've backported the changes from a personal override; I don't really know what the testing policy is, here.
Thanks; happy to …
> Add overrides for tensorflow-macos

- overrides/build-systems.json
Add missing build systems for `django-types`, `djangorestframework-types` and `slumber`.
> Add some missing build systems

- overrides/build-systems.json
A private project I'm building would otherwise fail with `ModuleNotFoundError: No module named 'setuptools'`.
> override: multiaddr

- overrides/build-systems.json
Make it possible to build projects depending on [blue](https://blue.readthedocs.io/).
Tested with the following files:
- <details><summary><tt>shell.nix</tt> (click to expand)</summary>
```nix
{ pkgs ? import <nixpkgs> { }
, poetry2nix ? import ~/dev/poetry2nix { }
}:
let
myAppEnv = poetry2nix.mkPoetryEnv {
editablePackageSources = {
my-app = ./src;
};
};
in myAppEnv.env
```
Where `~/dev/poetry2nix` is a clone of this git repo with this change.
</details>
- <details><summary><tt>pyproject.toml</tt> (click to expand)</summary>
```toml
[tool.poetry]
name = "foo"
authors = ["Raphael Borun Das Gupta <git@raphael.dasgupta.ch>"]
readme = "README.md"
python = "^3.10"
[tool.poetry.group.dev.dependencies]
blue = …
```
> build-systems: blue

- mk-poetry-dep.nix
`isSource` can be true e.g. when the package comes from a private registry but we can still figure out e.g. manylinux dependencies based on the fiename
> mkPoetryDep: always calculate dependencies in when installing from files

- overrides/build-systems.json
Entries sorted with `jq --raw-output --sort-keys < build-systems.json > new.json && mv new.json build-systems.json`.
> fix: Build systems for nixpkgs 22.11

- overrides/build-systems.json
- overrides/default.nix
- add build systems
- make fiona a `setuptools` format package
- add `libkrb5` to pymssql buildInputs
> build systems

- default.nix
- overrides/default.nix
This fixes #750.
A better fix for this might be to set e.g. `meta.isAlias = true` in [nixpkgs/blob/master/pkgs/top-level/python-aliases.nix](https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/python-aliases.nix#L27). Let me know if that is a better route :).
> Fix infinite recursion for aliases in pkgs/top-level/python-aliases.nix

- mk-poetry-dep.nix
Poetry also fetches submodules when downloading a git dependency
> Fetch git submodules

- overrides/build-systems.json
It seems to be needed (like the other scikit packages)
> scikit-image: add setuptools

- overrides/default.nix
Patch the dylib in the binary distribution to point to the nix build of libomp
> open3d: patch reference to openmp

- overrides/default.nix
Apparently this needs to be lowercase.
> mkdocs: fix `babel` package case

- overrides/default.nix
The expression `lib.optional cond [ 1 ]` returns `[ [ 1 ] ]` which is incorrect.
> overrides: Use lib.optional/lib.optionals correctly

- overrides/build-systems.json
As per the change log
<https://github.com/jupyter/nbformat/blob/e5dd9089c38b039e7fb874db9e141e01e2cce718/CHANGELOG.md#550>.
> fix: Use setuptools for nbformat 5.4.0

- overrides/default.nix
This partially reverts #865, since the override there doesn't work with `preferWheels = true;`.
> fix: revert mkdocs-material override

- overrides/build-systems.json
Changed their build system in https://github.com/jazzband/prettytable/commit/fabac93cb908418037c638a3303fd217da28ab10
I left setuptools as I don't know if we should keep it for compatibility with older versions of the package.
> overrides: build-systems: add hatchling to prettytable

- overrides/build-systems.json
hvac migrated their build system to poetry-core in this commit: https://github.com/hvac/hvac/commit/0ef445367afa4eb0ed5b85fa0d6658cf033f5751
I don't know if we should keep setuptools in the list for compatibility with older versions, let me know what you think.
> overrides: build-systems: add poetry-core to hvac

- pep425.nix
pyarrow ships macos x86_64 wheels based on macos 10.14 which we are missing as a wheel target. This PR fixes that.
> fix: allow macosx_10_14 wheels

- overrides/default.nix
`xlibsWrapper` was a transitional package to move from monolithic xorg package to modules. `nixpkgs` `python3Packages.pycairo` already removed `pkgs.xlibsWrapper`. This change follow the same change.
Bug: https://github.com/NixOS/nixpkgs/issues/194054
Closes: https://github.com/nix-community/poetry2nix/issues/863
> overrides: drop unused pkgs.xlibsWrapper package

- .github/workflows/ci.yml
This PR cancel existing GHA runs from single branch, so that when a new commit is pushed the currently running CI jobs for that branch/PR are cancelled.
> ci: cancel duplicate CI runs

- .github/dependabot.yml
- .github/workflows/ci.yml
This PR bumps our github actions versions and adds github actions version updates to the dependabot config.
> ci: bump github actions versions and add to dependabot

- README.md
- docs/edgecases.md
After battling with the `ModuleNotFoundError` I thought I might try to help with making the docs a bit clearer.
At least the I think that the changes would've helped me.
I was especially confused that you used `poetry` in the example I couldn't' really separate it from `peotry2nix` when debugging the error.
In addition the example used `self.poetry` and in the Matrix chat I was told (and got it working) that I had to use `super.poetry`.
> Extend docs

- .github/workflows/ci.yml
This PR runs the macos test builds on a single instance, so that PRs can hopefully get through the CI queue faster.
> ci: run macos jobs on a single instance

- overrides/build-systems.json
Hi!
`filelock` has [recently](https://github.com/tox-dev/py-filelock/commit/1cf8fcae4e688c60a078b1ec9286637141fb35bf#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R2-R3) switched to `hatchling` + `hatch-vcs`. This PR updates the corresponding override. I've kept setuptools and setuptools-scm in order to keep compatiblity with older versions (not sure if this is the recommended pattern for this).
> Update filelock build systems

- default.nix
- mk-poetry-dep.nix
Tested by temporarily setting `meta.broken = true;` in `mk-poetry-dep.nix`, and then
$ nix-build tools -A env
error: Package ‘python3.9-click-8.1.3’ in /home/user/h/poetry2nix/tools/poetry.lock:0 is marked as broken, refusing to evaluate.
a) To temporarily allo[...]
As you can see, the location of the lock file is reported, which is especially useful in Nixpkgs, which contains multiple lockfiles.
This used to be just the location of a generic python builder, which is generally not what the user wants.
I've exposed the `poetrylockPos` variable as a parameter that callers may set. This is intended as a contingency more so than a feature that is useful to users. That's why I've decided not to document it, because it would just add noise. I could make it internal, a let binding, if you …
> feat: Show lock location in package errors

- overrides/default.nix
Fix that opencv-python-headless tries to override opencv-python.
> overrides: opencv-python-headless

- overrides/build-systems.json
Make it possible to build projects depending on [pytest-flake8](https://github.com/tholo/pytest-flake8).
Tested with the following files:
- <details><summary><tt>shell.nix</tt> (click to expand)</summary>
```nix
{ pkgs ? import <nixpkgs> { }
, poetry2nix ? import ~/dev/poetry2nix { }
}:
let
myAppEnv = poetry2nix.mkPoetryEnv {
editablePackageSources = {
my-app = ./src;
};
};
in myAppEnv.env
```
Where `~/dev/poetry2nix` is a clone of this git repo with this change.
</details>
- <details><summary><tt>pyproject.toml</tt> (click to expand)</summary>
```toml
[tool.poetry]
name = "foo"
authors = ["Raphael Das Gupta <raphael.dasgupta@ost.ch>"]
readme = "README.md"
python = "^3.10"
[tool.poetry.group.dev.dependencies] …
```
> build-systems: pytest-flake8

- .github/ISSUE_TEMPLATE/issue-template.md
- don't make a bullet list in section "Additional context"
A bullet list would make sense if the code blocks would be part of the items. To make a code block part of a list item in Markdown, it would though have to be indentedwhich is either too laborious (when indenting all lines) or too confusing (when indenting only the opening line). If they aren't indented, they'd interrupt the list (thus effectively splitting it into 3 one-item lists) so let's instead just have the file names as prose-ish captions of the code blocks.
- add syntax highlighting
We do know what languages we expect in the files we ask the issue author to provide in the "Additional context" section, so let's set up proper syntax highlighting for them.
> Improve issue template: add syntax highlighting, don't make a bullet list

- overrides/build-systems.json
As per the [release log](https://github.com/tox-dev/py-filelock/releases/tag/3.9.0).
Should unblock https://github.com/linz/geostore/pull/2548.
> fix: Use hatchling for filelock >=3.9.0

- overrides/build-systems.json
> fix: Use setuptools-scm for python-ulid

- flake.nix
This avoids re-importing nixpkgs and thereby allocating a lot of additional memory. Instead pkgs.callPackage is used directly without creating a new nixpkgs instance.
Closes #652.
Replaces #868 which does not make sense at the moment, since it uses poetry2nix from nixpkgs instead of from the repo itself.
> flake: define packages without re-importing nixpkgs

- overrides/default.nix
This PR fixes an issue with wheel builds of shapely using newer versions of nixpkgs which seem to lack `GEOS_LIBRARY_PATH`.
> fix: fix shapely wheel build with newer versions of nixpkgs

- overrides/default.nix
This makes sure that share and include exist at $out so the pybind11 headers and cmake libraries can be found by cmake.
> Link include and share folders in pybind11 to top-level

- overrides/build-systems.json
For colander, consulate, pytest-ordering, uwsgidecorators, zk
> Add more build-systems overrides

- mk-poetry-dep.nix
Currently (as far as I can tell) all url dependency specs are treated as source tarballs, and specifying wheel urls fails. 
I need to add wheels manually from a non pypi source (https://data.pyg.org/whl/) which gave an error when trying to build it -  
a) didn't use the hash of the wheel, so I had to use --impure and 
b) thought that the wheel is a tarball, not a zip
c) didn't know how to use the wheel format if the url points to a wheel
This PR addresses those issues
> fix: wheel url parsing

- overrides/build-systems.json
I'm not sure if there's a typical format for these PRs, but this adds setuptools as a build dependency to the ligo-segments package to fix builds that depend on that package.
> Add setuptools build dependency to ligo-segments

- default.nix
This PR adds support for nativeCheckInputs, which appears to be the only supported way to introduce test dependencies in nixos-unstable-small as of https://github.com/NixOS/nixpkgs/commit/33afbf39f6f2a6b37e99f070ba7d17a28c416d02.
> fix: add `nativeCheckInputs` for newer nixpkgs

- overrides/build-systems.json
Should fix ModuleNotFoundError where setuptools was missing
> added override for python-hcl2 build system

- overrides/default.nix
Newer versions of automat do not depend on m2r anymore [1]. Because of this m2r might not end up being in poetry.lock along with automat, so "self.m2r" ends up refering to the nixpkgs pythonPackages.m2r. That package happens to be marked as broken in some conditions.
> overrides: automat: only add m2r to inputs for older versions

- .github/workflows/ci.yml
- overrides/build-systems.json
Uses a specific runner version (rather than "ubuntu-latest") to avoid replication issues when GitHub runners are updated.
> feat: Verify that build systems are sorted

- overrides/build-systems.json
- overrides/default.nix
fix: pydocstyle >= 6.2.0 build system 
[Selenium 4.0 uses Bazel to build python code][1]. Let's use the wheel to make it easier.
The override is split in two due to https://github.com/nix-community/poetry2nix/pull/948.
[1]: https://github.com/SeleniumHQ/selenium/blob/3ad153b16804695fb0448b43940b703b8022f45c/py/CHANGES#L368
> Updates to pydocstyle and selenium

- overrides/build-systems.json
I'm unable to explain why the CI is failing.
The parse error happens on a line that doesn't seem related to the lines I'm changing here.
> build-systems: add bencode-py

- fetch_from_legacy.py
This change parses the `index_url` of the source and extracts out the Basic Authentication `username` and `password` credentials, if they exist, to be used by the existing mechanism for netrc parsing.
The `index_url` is then reconstructed without the credentials, so that the rest of the index fetch can proceed as expected.
Previously, if one had a `pyproject.toml` with a custom source that had basic auth credentials in the URL, e.g.
```toml
[[tool.poetry.source]]
name = "private_source"
url = "https://username:password@pypi.example.com/pypi"
```
The `fetch_from_legacy.py` script would fail to parse, erronously splitting on the `:` thinking that whatever came after it was a numeric port identifier ala `https://example.com:8080`.
While embedding authentication credentials in an index URL …
> Parse pypi source indexes with basic auth creds

- .github/workflows/ci.yml
- overrides/build-systems.json
- shell.nix
- tools/default.nix
From the build:
> Package ‘python-2.7.18.6’ in
> /nix/store/n5hj62lgkwvz3gqnp4l4nxzjnadh7y54-source/pkgs/development/interpreters/python/cpython/2.7/default.nix:330
> is marked as insecure, refusing to evaluate.
and
> Python 2.7 has reached its end of life after 2020-01-01. See
> https://www.python.org/doc/sunset-python-2/.
Necessary to bump nixpkgs
<https://github.com/nix-community/poetry2nix/pull/996>.
> chore: Remove Python 2 compatibility

- README.md
Hopefully these can be simplified a bit - the `callPackage` syntax is very different from the default channel syntax.
> docs: Testing commands

- overrides/default.nix
As documented https://numpy.org/doc/stable/user/building.html, this enable parallel build for numpy
> numpy: Set NPY_NUM_BUILD_JOBS for parallel build

- .github/workflows/ci.yml
- overrides/build-systems.json
Add build system for:
- django-rest-swagger
- django-rosetta
- openapi-codec
- unipath
Also, Nix 2.14 broke cachix/install-nix-action, see:
https://github.com/cachix/install-nix-action/pull/163
> Update build-systems (and update CI install-nix-action)

- tests/override-default-support/default.nix
- tests/override-support/default.nix
Necessary to override package attributes in newer nixpkgs.
> fix: Use new `overridePythonAttrs`

- overrides/default.nix
`hikari` is a library to write discord bots in python and `hikari-lightbulb` is a command handler for `hikari`. Both of these can be used in poetry2nix with some minor tweaks
> Add overrides for hikari and hikari-lightbulb

- overrides/build-systems.json
- overrides/default.nix
Add the build system updates required for python-dxf. This adds `python-dxf` itself, `www-authenticate` and a new release of `cryptography`.
> Add the build system updates required for python-dxf

- overrides/build-systems.json
PiPi package `aws-sso-utils` requires Poetry
Tested and working on my branch
pyproject.toml:
```toml
[tool.poetry]
name = "resource-accounts"
description = "IaC for resource accounts"
authors = ["Ariel Richtman <ariel.richtman@silverrailtech.com>"]
python = "^3.10"
diagrams = "*"
aws-sso-util = "*"
[tool.poetry.group.dev.dependencies]
pre-commit = "*"
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```
flake.nix
```nix
{
inputs = {
nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
utils = {
url = github:numtide/flake-utils;
};
poetry2nix = {
url = "github:arichtman/poetry2nix/aws-sso-util-override";
inputs.nixpkgs.follows = "nixpkgs";
};
};
outputs = { nixpkgs, utils, self, poetry2nix, ... }: …
```
> fix: aws-sso-util needs Poetry

- README.md
Was testing out `poetry2nix` and also new to `poetry` for that matters. I found very limited documentation on the need of `[tool.poetry.scripts]`. If I do not have this stanza, then the output derivation evaluates without error, but produces nothing!
Also, the existing README does point out that the output derivation for webserver to be ran with `hypercorn` or `uvicorn` should be an environment, but there is a simple way to just output to a binary using `pkgs.writeShellApplication`, effectively providing abstraction over the ASGI runtime to be used.
Hopefully this saves new devs' time!
> +docs: build binary with `mkPoetryApplication` and build webserver wrapper binary

- overrides/build-systems.json
> Add build system for fastapi-utils

- .github/workflows/ci.yml
See
<https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/> and
<https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files>.
The deprecated syntax will start breaking "1st June 2023".
> fix: Use new output syntax

- overrides/build-systems.json
Changes the build dependency for strawberry from poetry-core to full poetry. I'm not sure what could have changed since I assume the build was working before, but this seemed to be necessary to get my build working and [their pyproject.toml](https://github.com/strawberry-graphql/strawberry/blob/main/pyproject.toml#L33) seems to use full poetry.
Not related to this particular PR, but apparently strawberry is looking at moving away from poetry: strawberry-graphql/strawberry#2199, strawberry-graphql/strawberry#2497 in case someone finds this PR in search.
> strawberry: poetry-core -> poetry

- overrides/build-systems.json
- tests/default.nix
- tests/gitlint/default.nix
- tests/gitlint/poetry.lock
- tests/gitlint/pyproject.toml
Looks like it must be kept in tandem with gitlint-core (#1051).
In draft until I figure out why this fix isn't working for my work project. Even with poetry2nix 1.40.1 (nixpkgs-22.11 a08bae02236cbb2692e1230e40ddf7aff3e2225e) and this override
```nix
{
gitlint = super.gitlint.overridePythonAttrs (
old: {
propagatedBuildInputs = old.propagatedBuildInputs or [ ] ++ [
self.hatchling
self.hatch-vcs
];
}
);
}
```
the build seems to still be missing hatch-vcs somehow.
```text
Sourcing python-remove-tests-dir-hook
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing python-namespaces-hook
Sourcing pip-build-hook
Using pipBuildPhase
Using …
```
> fix: gitlint needs hatch-vcs

- overrides/default.nix
My build of [Emmett](https://emmett.sh/) was failing due to this table not containing the latest versions of [Granian](https://github.com/emmett-framework/granian/tags).
This is intended to add the needed versions.
> Bumped granian version to 0.3.1

- default.nix
- flake.nix
- overlay.nix
- tests/default.nix
Also remove the completely unused `poetry` argument from `default.nix` as to not confuse people even more.
> fix(flake): build poetry with correct poetry2nix

- overrides/build-systems.json
This should allow building projects that depend on sqlmodel or psycopg[pool].
> Add setuptools to psycopg-pool and poetry-core to sqlmodel build deps

- overrides/build-systems.json
Ran into the following errors without having these overrides:
`error: builder for '/nix/store/azy98pgyfzidhhs4zi5d2fyys5i0kg09-python3.10-beautifulsoup4-4.12.2.drv' failed with exit code 2;
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'hatchling'`
`error: builder for …
> Update overrides for beautifulsoup4, url-normalizer

- overrides/build-systems.json
- overrides/default.nix
* pao needs setuptools to build.
* munch needs setuptools at runtime (ugh!)
* pao forgot to include a dependency (pyutilib.)
> Fix PAO and its dependencies.

- overrides/default.nix
I ran into the following error
```
warning: Git tree '/Users/raphael/dev/text-generation-webui' is dirty
trace: warning: Unknown orjson version: '3.8.10'. Please update getCargoHash.
fetching submodules of 'https://github.com/huggingface/peft'warning: refname 'HEAD' is ambiguous.
error: hash mismatch in fixed-output derivation '/nix/store/xky1yz2rd8wl9xdnp4ys4rhmpg3ccb1y-orjson-3.8.10-vendor.tar.gz.drv':
specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
got:    sha256-AcrTEHv7GYtGe4fXYsM24ElrzfhnOxLYlaon1ZrlD4A=
```
and it wasn't immediately clear to me how to use the overrides to override that.
If you have any pointers as to how to override that locally, I'd be happy to make a doc PR.
> orjson: update getCargoHash

- fetch_from_legacy.py
Parser will fail to parse if string is not decoded.
> Decode string using utf-8

- overrides/build-systems.json
Fixes https://github.com/nix-community/poetry2nix/issues/1127 when using Python 3.11
Maybe there is a fix for this to work with Python 3.10, but it seems like versioneer only [supports toml at python 3.11+](https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/versioneer/default.nix#L25).
> Set versioneer for pandas

- overrides/build-systems.json
Hello there :wave: 
I was trying to build a project that had a dependency on `tkcalendar` and I got this error:
```
λ nix build
error: builder for '/nix/store/b9dplp5dfmdf8ywg3l0c3awj10vdivkn-python3.10-tkcalendar-1.6.1.drv' failed with exit code 2;
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
> …
```
> Add setuptools to tkcalendar

- overrides/default.nix
It happens every so often that the nixpkgs that `poetry2nix` uses, defines overrides for packages that don't exist in the nixpkgs that we use (nixos-22.11).
This patch allows us to still use the newer version of poetry2nix.
> Don't fail to apply overrides if a package does not exist (yet)

- overrides/default.nix
Copies fix for nixpkgs.opencv in https://github.com/NixOS/nixpkgs/pull/225378
> overrides: add Accelerate framework for opencv on darwin

- overrides/default.nix
This small patch adjust the DuckDB overwrite to work with the current package structure that relocate [setup.py](https://github.com/duckdb/duckdb/blob/master/tools/pythonpkg/setup.py) (from `/` -> `/tools/pythonpkg`). I came across this error when trying to use DuckDB with jupyenv. The actual source for the fix is nixpkg's version of [python3Packages.duckdb](https://github.com/NixOS/nixpkgs/blob/3ed18a352739221ebaba0d11c38a2158faa29887/pkgs/development/python-modules/duckdb/default.nix#L22) that includes this adjustment already.
> fix: DuckDB overwrite

- default.nix
Currently it is not possible to remove the "dev" group when using mkPoetryEnv: the "dev" group is still built because it is part of the `checkGroups`. To be able to avoid this, I opted to add `checkGroups` to `mkPoetryEnv`, just like what you would be able to in `mkPoetryApplication` and `mkPoetryPackages`.
This is a step towards resolving https://github.com/nix-community/poetry2nix/issues/627 properly.
> mkPoetryEnv: add checkGroups

- overrides/build-systems.json
See https://github.com/urllib3/urllib3/commit/8dda1974ae51839304f8517ab7993006c0d9db2e for the commit to change from `flit_core` to `hatchling`.
> urllib3: Used flit-core until 2.0.2 and hatchling since

- lib.nix
There is a bunch of overrides that relies on the `src.isWheel` attribute, which is not set at all when `fetchFromLegacy` is used.
> lib: Include isWheel for fetchFromLegacy

- overrides/default.nix
The lack of this would trigger runtime errors like:
```
File "/nix/store/sp8sipvizxaadiws38h9x0szyn3m63a7-python3.9-web3-trio-1.0.3/lib/python3.9/site-packages/web3_trio/transaction.py", line 6, in <module>
import eth_account
File "/nix/store/2mf213pkc3yqpiimqpc8vsh9az45wqdi-python3.9-eth-account-0.7.0/lib/python3.9/site-packages/eth_account/__init__.py", line 1, in <module>
from eth_account.account import (
File "/nix/store/2mf213pkc3yqpiimqpc8vsh9az45wqdi-python3.9-eth-account-0.7.0/lib/python3.9/site-packages/eth_account/account.py", line 18, in <module>
from eth_keyfile import (
File "/nix/store/yxikh4an09sax2imjc7f4qf8anlr7mnc-python3.9-eth-keyfile-0.6.1/lib/python3.9/site-packages/eth_keyfile/__init__.py", line 3, in <module>
import pkg_resources
ModuleNotFoundError: No module named …
```
> overrides: eth-keyfile: runtime dep on setuptools

- overrides/build-systems.json
This PR adds build system overrides for some obscure packages.
[pylint-plugin-utils](https://github.com/PyCQA/pylint-plugin-utils) recently [switched to poetry](https://github.com/PyCQA/pylint-plugin-utils/commits/master/pyproject.toml), so I added `poetry` in addition to `setuptools` in order to support both pre- and post-poetry versions for now.
> Add build system overrides

- overrides/build-systems.json
Hi,
I have a project that uses the dask set of tools and wanted to take advantage of poetry2nix. Since they all rely on pandas 2.0, I believe they need "versioneer" listed in the build-systems overrides. Also added entries for pykube-ng and kopf which is used by dask_kubernetes.
This was enough to get everything to build in the project, however If this is the wrong way to do this feel free to close!
> Add setuptools for dask tooling.

- overrides/build-systems.json
- Add build system (setuptools) for genson
- Add build system (poetry) for jsonref >= 0.3.0, < 1.1.0
> Add build systems for genson, jsonref

- README.md
As far as I can tell, `defaultPoetryOverrides` is already a list.
> docs: Avoid nested list of overrides

- overrides/default.nix
In version 2.0.0 released in April last year this override is not needed and causes issues when building from wheel.
> jsondiff override not needed anymore

- README.md
I'm sure this could be expanded upon, and maybe this PR can provide the impetus for that.
> FAQ: Clarify poetry2nix does not use nixpkgs for Python packages

- overrides/default.nix
I was wondering why recommonmark did not appear in my environment :)
I've made that mistake a few times as well and it's rather confusing, is there a pattern which could avoid the name repetition?
> Fix override recommonmark and rich mixup

- overrides/build-systems.json
This package doesn't build without setuptools.
> overrides: discord-py

- overrides/default.nix
It's an optional dependency (AFAICT) and the current version of mesa is broken in nixpkgs
> open3d: don't include mesa on Darwin

- overrides/default.nix
Safer overrides made fallbacks when buildInputs don't exist
https://github.com/nix-community/poetry2nix/pull/250/commits
But there were 3 missing cases I caught.
> patch missing old buildinputs

- default.nix
- overrides/build-systems.json
- overrides/default.nix
[`jsonschema` 4.18.0](https://github.com/python-jsonschema/jsonschema/releases/tag/v4.18.0) gained a bunch of new dependencies which need overrides to build:
- [`rpds-py`](https://github.com/crate-py/rpds):
- uses Rust and Cargo, and therefore the override would require updating the Cargo hash after every new release;
- [`referencing`](https://github.com/python-jsonschema/referencing):
- uses the `hatchling` and `hatch-vcs` build system packages;
- declares classifiers which are not accepted by `hatchling` 1.13.0 (the minimum requirements are apparently `hatchling` >= 1.14.0 and `trove-classifiers` >= 2023.4.25); updating `hatchling` would be really complicated, so the offending classifiers are patched out in `postPatch`;
- [`jsonschema-specifications`](https://github.com/python-jsonschema …
> Update overrides for `jsonschema` 4.18.0

- default.nix
The CI test `cli` broke:
```
$ nix-build --dry-run --keep-going --show-trace tests/default.nix -A cli
error:
… from call site
at /home/runner/work/poetry2nix/poetry2nix/default.nix:464:9:
463|   /* Poetry2nix CLI used to supplement SHA-256 hashes for git dependencies  */
464|   cli = import ./cli.nix {
|         ^
465|     inherit pkgs lib;
error: function 'anonymous lambda' called with unexpected argument 'version'
at /home/runner/work/poetry2nix/poetry2nix/cli.nix:1:1:
1| { pkgs ? import <nixpkgs> { }
| ^
2| , lib ? pkgs.lib
nix-build-uncached: --dry-run failed: exit status 1
```
Remove the leftover `version` argument to fix that.
> Fix CLI after removal of `version`

- pep425.nix
This PR is two-part, mainly aiding `preferWheels=true`.
---
The `m` abi flag has [since python 3.8](https://docs.python.org/3/whatsnew/3.8.html#build-and-c-api-changes) become obsolete, as builds with and without pymalloc are now compatible.
---
Some wheels use the abi `linux` instead of `manylinux`. [Pytorch3d](https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py38_cu113_pyt1110/download.html) (via [this](https://github.com/facebookresearch/pytorch3d/blob/main/INSTALL.md#3-install-wheels-for-linux)) is one such example. Both poetry and pip seem to accept it, so why not?
> preferWheels improvements

- .github/workflows/ci.yml
- tests/default.nix
It seemingly broke and just returns zero regardless of builds having to be done.
> ci: Get rid of nix-build-uncached

- overrides/build-systems.json
Execnet 2.0.2 now requires hatchling and hatch-vcs to build.
> Extend execnet overrides

- README.md
It seems GitHub generates all-lowercase heading anchors.
> docs: Fix internal links

- overrides/default.nix
- tests/rpds-py-no-wheel/poetry.lock
- tests/rpds-py-no-wheel/pyproject.toml
- tests/rpds-py-wheel/poetry.lock
- tests/rpds-py-wheel/pyproject.toml
Support new versions of rpds-py
> chore: add rpds-py versions hashes and bump version in tests

- overrides/build-systems.json
First time contributor to this repo.  I am not sure of what the best method for testing this update is _in situ_.  I found that this override fixed an issue with building `sphinx-rtd-theme` with poetry2nix (i.e., `sphinxcontriib-jquery` not being able to find `flit_core`).
> Update build-systems.json for sphinxcontrib-jquery

- overrides/default.nix
Adds the build hash for the cryptography dependency
> Add cryptography==41.0.3 hash

- overrides/build-systems.json
- overrides/default.nix
Some overrides I've ran into while packaging an application.
The gunicorn one is weird since they added a runtime dependency with https://github.com/benoitc/gunicorn/pull/2963 but did not declare it.
The runtime dependency on setup-tools might disappear soon as well: https://github.com/benoitc/gunicorn/issues/2747
> overrides for gunicorn, service-identity and flask-discord-interactions

- mk-poetry-dep.nix
Fixes an issue where branches not created from upstream `HEAD` could not be found
> fix: also use `allRefs = true` when branch is given

- overrides/build-systems.json
@adisbladis this is my first attempt at this, the nix override equivalent that makes it work locally is:
```
altair = super.altair.overridePythonAttrs (
old: { nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [ self.hatchling ]; }
);
```
> Add hatchling to altair

- overrides/default.nix
Explicitly list the modules we depend on instead of relying on qt5.full. Also removes deprecated and unmaintained qt5.qtwebkit dependency.
> overrides/pyqt5: be explicit about dependencies

- overrides/default.nix
I added `meson-python` and `pkg-config` as dependencies for contourpy when the version is >= 1.1.0.
The latest version of contourpy was not building with the older version of dependencies. It seems that they changed the build system. (see https://contourpy.readthedocs.io/en/latest/changelog.html#v1-1-0-2023-06-13)
This PR should fix the build issue.
Tested versions of contourpy:
- 0.0.5
- 1.0.7
- 1.1.0 (uses the newer build system)
> overrides/contourpy: add dependency to meson on >=1.1.0

- cli.nix
Basically make the `cli` derivation to conform with `pkgs.lib.getBin` "standard", so that flakes can recognize the binary
Before:
```
% ❯ nix run .#
error: unable to execute '/nix/store/8ich1m9piml9g77ik965ixnn27g6gxqq-poetry2nix-cli
-0/bin/poetry2nix-cli': No such file or directory
```
After:
```
% ❯ nix run .#
warning: Git tree '/Users/htran/local_repos/poetry2nix' is dirty
usage: .poetry2nix-cli-wrapped [-h] {lock} ...
.poetry2nix-cli-wrapped: error: the following arguments are required: subcommand
```
> chore!: make cli package/app compatible with flake

- overrides/build-systems.json
- overrides/default.nix
* `cachecontrol` switches to flit-core since 0.13.1: https://github.com/psf/cachecontrol/commit/a2f92fdee213729db1dbd35ede7efb1ad8e87617
* `notebook` switches to hatch backend since 7.0.0:
https://github.com/jupyter/notebook/commit/614e4780b88f5cf5e2bfda39a55357a0be5ef161
And since it require `jlpm` command which is a npm wrapper from `jupyter` package at build time, I have to add it to nativeBuildInputs.
> overrides: add build system for cachecontrol and notebook

- overrides/build-systems.json
Note that manually overriding the `buildInputs` in a flake actually results in:
```sh
> Executing pythonRemoveTestsDir
> Finished executing pythonRemoveTestsDir
> pythonCatchConflictsPhase
> /nix/store/q2zpnf017gccs9w9mb0ikdqhkf0k5v82-catch_conflicts.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>   import pkg_resources
> Found duplicated packages in closure for dependency 'hatchling':
>   hatchling 1.18.0 (/nix/store/zjkajhjjz7wis9yvm3gwvphifx3hiav2-python3.10-hatchling-1.18.0/lib/python3.10/site-packages)
>   hatchling 1.18.0 (/nix/store/2jy9c8hbk8v0rk45zv8680srs1jky977-python3.10-hatchling-1.18.0/lib/python3.10/site-packages)
>
> Package duplicates found in closure, see above. Usually this …
```
> `httpcore`: `setuptools` -> `hatchling` in 0.18.0+

- .github/workflows/ci.yml
- README.md
- overrides/build-systems.json
- overrides/sort-build-systems.jq
Closes #1320.
[`jq` does not yet support sorting by locale](https://github.com/jqlang/jq/issues/2218), so there are some slightly awkward sorts like "hatch-vcs" before "hatchling".
FYI @moonshxne @cpcloud
> feat: Sort override build systems more strictly

- overrides/build-systems.json
Similar to the other textual-* packages, seems low value to add a test for each. I'm inclined to just merge this directly but I'll defer to my co-maintainers.
> build-systems: add override for textual-fastdatatable

- overrides/default.nix
Watchfiles 0.21.0 was released so I added a hash for it.
> Update watchfiles hash for 0.21.0

- lib.nix
- mk-poetry-dep.nix
- pep425.nix
> Use PEP-599 platform definitions from pyproject.nix

- overrides/default.nix
Adds support for pycurl via override. Tested on GNU/Linux with NixOS. Fixes #1283 
`pyproject.toml`:
```toml
[tool.poetry]
name = "pycurl-test"
authors = ["nhr-zib <kobschaetzki@zib.de>"]
python = "^3.10"
pycurl = "7.45.2"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```
`flake.nix`:
```nix
{
description = "pycurl test";
inputs = {
flake-utils.url = "github:numtide/flake-utils";
nixpkgs.url = "github:NixOS/nixpkgs/nixos-23.05";
poetry2nix = {
url = "github:bzadm/poetry2nix/master";
inputs.nixpkgs.follows = "nixpkgs";
inputs.flake-utils.follows = "flake-utils";
};
};
outputs = { self, poetry2nix, nixpkgs, flake-utils }:
flake-utils.lib.eachDefaultSystem (system:
let pkgs = …
```
> pycurl: Add curl as a depedency

- dev/treefmt.nix
No need to manually pass things around and invoke programs using `sh`, treefmt already has programs for the tools we use.
> refactor(treefmt): use builtin treefmt programs

- overrides/build-systems.json
aiofiles: https://github.com/Tinche/aiofiles/releases/tag/v23.2.0
> overrides: add dynaconf, quart-flask-patch; fix aiofiles

- .github/workflows/ci.yml
- flake.nix
- tools/default.nix
> fix: use poetry2nix from top-level when importing `./tools`

- .github/workflows/ci.yml
- flake.nix
Clean up the build-systems CI check.
> ci: clean up builds systems ci check

- overrides/default.nix
> overrides.pyqt6: Only do autoPatchelf stuff on wheels

- tools/auto_version.py
SemVer has two rules that the previous scheme violates:
1. major/minor/patch numbers can't start with a leading 0. Changing `%d` to `%-d` removes the leading zero. I also applied it to the year just in case :):
```
>>> print(now.strftime(f"%Y.%m.%d"))
2023.09.01
>>> print(now.strftime(f"%Y.%-m.%-d"))
2023.9.1
```
2. there can't be four dot-separated sections of the version. In this PR, I merge the year and month into one field (with a leading zero on the month!) so the seconds is the "patch" version, like this:
```
>>> print(now.strftime(f"%-Y%m.%-d.{modifier}"))
202309.1.82922
```
I understand semantically poetry2nix isn't following semver, but I wonder if you're open to making the published tags semver parsable?
> auto_version: make the tags parse under semver

- overrides/build-systems.json
Multiple packages that require setuptools all related to pulumi
> overrides: add build systems

- lib.nix
PEP508 supports `requires` lines that have leading/trailing spaces, such
as:
requires = ["poetry-core >=1.7.0"]
Poetry apparently handles this fine, but poetry2nix doesn't. This commit
uses proper parsing with the pep508 library.
> fix: use pep508.parseString for requiredPkgs parsing 

- overrides/build-systems.json
While building a small project, I was hit with
error: builder for '/nix/store/wqnn0z60fli4bsxhg98cpqdr2w0w9b6q-python3.11-python-lsp-ruff-1.6.0.drv' failed with exit code 2;
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'setuptools'
>
>
For full logs, run 'nix log …
> Add overrides for pygls and python-lsp-ruff

- overrides/build-systems.json
> overrides: add setuptools to pyxis build

- overrides/default.nix
Hopefully does what it says on the tin! `nix-build --keep-going --show-trace tests/default.nix` seems to succeed after this change (not sure if what I've changed is actually tested though).
> chore(rpds-py): add getCargoHash for 0.13.0

- overrides/build-systems.json
- overrides/default.nix
- Updated hash for rpds-py 0.13.1
- Added bravado override
- Pygment switched build system to hatchling
> Various fixes

- overrides/build-systems.json
This appears to have been added in #1329 without comment, but is now causing a duplicate dependency failure for me:
```console
python3.11-multidict> Found duplicated packages in closure for dependency 'pip':
python3.11-multidict>   pip 23.2.1 (/nix/store/slhj69him45n2pck7wkknnffi4ay0jy0-python3.11-pip-23.2.1/lib/python3.11/site-packages/pip-23.2.1.dist-info)
python3.11-multidict>   pip 23.2.1 (/nix/store/rqch5axq9ky53cny22zwyvq93g0w68jn-python3.11-pip-23.2.1/lib/python3.11/site-packages/pip-23.2.1.dist-info)
python3.11-multidict> Package duplicates found in closure, see above. Usually this happens if two packages depend on different version of the same dependency.
```
> overrides: multidict -> remove pip dependency

- overrides/build-systems.json
yarl moved to their own build backend: https://github.com/aio-libs/yarl/commit/98eac52a7add38dd770f2baf95f0c4c5a62165e5
The build currently fails if you build the wheel without cython: https://github.com/aio-libs/yarl/issues/962
> overrides yarl: add build-systems

- overrides/build-systems.json
> Add build-systems override for rich-click

- overrides/build-systems.json
Note: I tried testing this in my project by using my branch rather than upstream, but it seemed to have no effect. Since this is very similar to other overrides, I'm just going to assume that was an issue with the way I was testing the override.
> overrides: add pydevd-pycharm

- overrides/default.nix
The pkgconfig alias has been dropped from nixpkgs in https://github.com/NixOS/nixpkgs/pull/254418
fixes https://github.com/nix-community/poetry2nix/issues/1446
> do not use obsoleted pkgconfig alias, use pkg-config directly

- overrides/default.nix
Pretty sure this is the right hash, but I'm not sure how to test it.
> overrides: add cargo hash for rpds-py 0.13.2

- overrides/build-systems.json
> overrides: lnurl

- overrides/default.nix
```
trace: warning: Unknown cryptography version: '41.0.6'. Please update getCargoHash.
error: hash mismatch in fixed-output derivation '/nix/store/b5j2nrwkffbxmjgm9d7y2hddx7j4ygvc-cryptography-41.0.6-vendor.tar.gz.drv':
specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
got:    sha256-E7O0035BnJfTQeZNAN3Oz0fMbfj45htvnK8AHOzfdcY=
```
> overrides: add hash for cryptography 41.0.6

- overrides/default.nix
> overrides/matplotlib: only add setuptools-scm-git-archive for older versions

- overrides/default.nix
Yes, it's unlikely that ruff's maintainer (or an attacker who has broken into or MITM'd github's API) would try to attack us through malicious tag names, but why allow the possibility?
> Update hashes for ruff; fix injection vulnerabilities in paired script

- overrides/default.nix
not included in this MR (in case we didn't want to adjust the tests from their current state) - I updated the test pyproject.toml version to `4.1.2`, reran `poetry lock` and ran the test with 
```bash
nix-build --attr bcrypt tests/default.nix
```
> overrides: add cargo hash for bcrypt 4.1.2

- overrides/default.nix
> overrides: add cargo hash for rpds-py 0.14.2 to 0.16.2

- overrides/build-systems.json
This is what I need to get https://github.com/joaomdmoura/crewAI-examples/tree/main/trip_planner running,
an example project for https://github.com/joaomdmoura/crewAI, except for the following override:
```
overrides = p2n.defaultPoetryOverrides.extend (self: super: {
unstructured = super.unstructured.overridePythonAttrs (old: rec {
src = super.pkgs.fetchFromGitHub {
owner = "Unstructured-IO";
repo = "unstructured";
rev = "refs/tags/${old.version}";
sha256 = "sha256-kpT/rcAFlPmDVuayVgW9WHI9MT+2R6AC8Z/8+vDHYVw=";
};
});
});
};
```
That overlay was required because the source distribution for `unstructured` is missing a bunch of files.
I thought getting the overlay into a state that could be committed here wasn't worth it.
[Contribution](README.md#contributing) checklist (recommended but …
> overrides: add crewAI and its missing dependencies

- overrides/default.nix
Updates the cargo hash for [ruff](https://docs.astral.sh/ruff/) version 0.1.12.
> Update cargo hash for `ruff` v0.1.12

- overrides/default.nix
> chore(rpds-py): add getCargoHash for 0.17.1

- overrides/default.nix
> overrides: add hash for cryptography 42.0.2

- hooks/default.nix
- overrides/default.nix
The upstream Nixpkgs renamed `pythonForBuild` to `pythonOnBuildForHost` and made `pythonForBuild` emit warnings: NixOS/nixpkgs#265764.  Adjust the poetry2nix code to avoid warnings with the new version, while still keeping compatibility with the old one.
> Adjust for renaming of `pythonForBuild` to `pythonOnBuildForHost`

- overrides/default.nix
m2crypto needs swig at build time and openssl libs at run time.
https://gitlab.com/m2crypto/m2crypto/-/blob/master/INSTALL.rst?ref_type=heads#id1
> fix(m2crypto): Update missing dependencies for M2Crypto

- overrides/build-systems.json
> fix(types-ujson): specify setuptools as a build system for types-ujson.

- overrides/default.nix
There are default overrides for  `pytorch-lightning`  that attempt to handle what must have previously been something like a nested tarball. I removed these and what previously resulted in
```bash
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
tar: This does not look like a tar archive
```
during installation proceeded as expected. This is at least true when I source the boundaries of the `[1.9.4 2.1.3]` version range in a test flake on Darwin aarch64 and Linux x86_64 systems. I am posting this PR to mark the issue and discuss the necessity of retaining these `unpackPhase` customizations with version guards for backward compatibility versus removing them altogether.
I could add such guards if I knew where things changed, but I didn't manage to bisect where that is …
> fix(pytorch-lightning): disable unpackPhase override

- overrides/default.nix
> overrides: add hash for cryptography 42.0.3

- overrides/build-systems.json
> overrides: add ninja-python, alabaster and quantile-python

- overrides/build-systems.json
python-firebase needs `setuptools`, see here: https://github.com/ozgur/python-firebase/blob/0d79d7609844569ea1cec4ac71cb9038e834c355/setup.py#L5
I hope I added it correctly!
> fix(python-firebase): Add "setuptools" to build-systems.json

- flake.lock
- overrides/default.nix
- tests/ruff/poetry.lock
- tests/ruff/pyproject.toml
Also updates flake.lock since ruff 0.2.2 needs at least rust 1.74.
> overrides: add hashes for ruff 0.2.{1,2}

- README.md
The FAQ question is about the choice between the two alternatives (a) "wheels" vs. (b) "sdists", not about whose sdists they are.
> docs: fix typo: "wheels our sdists" → "wheels or sdists"

- vendor/pyproject.nix/fetchers/default.nix
When using flakes, pure evaluation mode prevents arguments supplied by `-I` such as `-I NETRC=...` from being passed, instead returning an empty list, which makes using the `NETRC` option for fetching proprietary code impossible when using Flakes. This PR simply adds NETRC to the list of `impureEnvVars` to be passed if set in the nix-daemon service via `systemd.services.nix-daemon.serviceConfig.Environment="netrc=/path/to/netrc"` if you are using pure evaluation mode. This PR makes `NETRC` useful for both flakes and non-flakes usage.
```
user: matthew ~
❯ nix repl --pure-eval
Nix 2.21.2
Type :? for help.
nix-repl> builtins.nixPath
[ ]
user: matthew ~
❯ nix repl
Nix 2.21.2
Type :? for help.
nix-repl> builtins.nixPath
[ { ... } ]
```
> vendor: pass NETRC via impureEnvVars if inPureEval

- overrides/build-systems.json
I discovered some new build system requirements using poetry2nix.
Updated build system overrides for:
* ~~`cloudpickle`~~ -> already fixed in https://github.com/nix-community/poetry2nix/pull/1559
* `dask`
* ~~`dnspython`~~ -> already fixed in https://github.com/nix-community/poetry2nix/pull/1559
* `frozenlist`
* `yarl`
Added build system overrides for:
* `fastapi-sessions`
* `gcloud-aio-auth`
* `gcloud-aio-storage`
* `maphash`
> overrides: Add and update build system overrides

- overrides/default.nix
In #1447 some references of `pkgs.pkgconfig` were
change to `pkgs.pkg-config` which was correct, as
the `pkgs.pkgconfig` is a deprecated alias for the latter. However that change _also_ changed
`self.pkgconfig` to `self.pkg-config`: the `self`
here is _not_ the same as `pkgs`. The `self`
refers to Python package set so it formerly
referred to the `pkgconfig` Python package.
There's no `pkg-config` Python package so this
code just fails to evaluate, resulting in #1564.
In first place, it looks like using
`self.pkgconfig` was probably wrong and we wanted
the `pkgs.pkg-config` so I simply make that change instead.
Fixes #1564.
> Refer to right pkg-config thing

- overrides/build-systems.json
> Mark altgraph, macholib, and pyinstaller-hooks-contrib as needing setuptools

- overrides/build-systems.json
- overrides/default.nix
The marshmallow one, it now has both `flit-core` and `setuptools`, I saw some other code above having both, thought that's probably simpler (might result in an extra unnecessary download/build, but probably not a big problem), than selecting based on version.
The pillow fix should help https://github.com/nix-community/poetry2nix/issues/1139
From the README.md
> * This project uses [nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt) for formatting the Nix code. You can use nix-shell --run "nixpkgs-fmt ." to format everything.
Seems like there are a couple of unformatted things, when I ran this -- I only used the formatting on the newly added lines, to avoid noise.
> overrides: add gdspy, gdstk, update marshmallow, fix pillow 9.5.0

- .github/workflows/ci.yml
Allow builds that do not require one-at-a-time runs to run concurrently
> ci: allow more concurrency in CI

- README.md
- bin/poetry2nix
- default.nix
- docs/edgecases.md
- flake.nix
- mk-poetry-dep.nix
- overrides/default.nix
- tests/cairocffi-wheel/default.nix
- tests/canonical-module-names/default.nix
- tests/canonical-module-names/poetry-git-overlay.nix
- tests/composable-defaults/default.nix
- tests/contourpy-no-wheel/default.nix
- tests/contourpy-wheel/default.nix
- tests/file-src-deps-level2/default.nix
- tests/file-src-deps/default.nix
- tests/git-deps-pinned/poetry-git-overlay.nix
- tests/grpcio-wheel/default.nix
- tests/markdown-it-py-wheel/default.nix
- tests/override-default-support/default.nix
- tests/override-support/default.nix
- tests/panel-wheels/default.nix
- tests/path-deps-develop/default.nix
- tests/pep600/default.nix
- tests/prefer-wheel/default.nix
- tests/rpds-py-wheel/default.nix
As my company is evaluating to use this library for a few teams, i would like to improve the documentation.
Here's a first step:
Align the overlays in code and examples with newer Nixpkgs convention `final: prev:`
@adisbladis 
Feel free to edit, request changes or remove this PR.
> Improve documentation: Synchronize overlays self super to final prev style

- overrides/default.nix
Conflicts with `llamaindex-cli` file from [llama-index-cli](https://pypi.org/project/llama-index-cli/) package
Without this change, I get this error:
```nix
> error: collision between `/nix/store/561w0gwm3g4wgyfq3p1z4lfzzb3wiwcy-python3.11-llama-index-cli-0.1.12/bin/.llamaindex-cli-wrapped' and `/nix/store/qp79rzbl0r73bwkn5kn6nr0xmis2zn9i-python3.11-llama-index-0.10.30/bin/.llamaindex-cli-wrapped'
```
I removed the conflict from `llama-index`, since it seems more appropriate for `llama-index-cli` to provide the `llamaindex-cli` command.
Not sure that this is the right approach and can update it it there's a better way, but it worked for my use case.
> Patch llama-index to remove conflicting file

- overrides/build-systems.json
- overrides/default.nix
These are all the overrides needed to get a large, old Django app to build by default. I tested building a poetryEnv for that app locally with this branch and it's working as expected!
I'm not entirely sure why `setup.py` is sometimes missing for `pytest-django` and `daphne`, but I'm guessing it has something to do with `preferWheels` since we have that enabled. It looked like other overrides already have similar file checks.
> Add and fix several django-related build system overrides

- overrides/default.nix
- tests/ml-stack/default.nix
This symlinks all the .so libraries to $out/lib/ so the autopatchelf hook can find them, instead of relying on torch's inbuilt magic to find the libraries.
I've also formatted it as a separate overlay that generates the override for all the nvidia packages.
> nvidia: use different method for making libraries work

- overrides/build-systems.json
> fix(build-systems): use hatch-fancy-pypi-readme for openai >= 1.15.0

- overrides/default.nix
- tests/ruff/poetry.lock
- tests/ruff/pyproject.toml
Adds hash for ruff 0.4.4, potentially fixing hash errors if ruff 0.4.4 is in poetry packages:
```
trace: warning: Unknown ruff version: '0.4.4'. Please update getCargoHash.
trace: warning: Unknown ruff version: '0.4.4'. Please update getRepoHash.
```
---
> overrides: add hash for ruff 0.4.4

- overrides/default.nix
- tests/matplotlib-3-6/default.nix
- tests/matplotlib-3-7/default.nix
- tests/matplotlib-3-9/default.nix
This little patch allows skipping the patching of a source file in matplotlib if a wheel is used, and it is thus not available. For me this "works" but maybe there is some objection to doing it this way.
Can `preferWheels = true` be detected/accessed inside the override?
> fix matplotlib override

- overrides/build-systems.json
> overrides: peewee build system cython->cython_0

- overrides/default.nix
Poetry2nix tensorflow-macos overlay creates an implicit dependency on tensorflow, so that you always end up trying to install the normal tensorflow, which sometimes doesn't work: Some older tensorflow versions have broken ARM packages or don't exist at all; sometimes you just want tensorflow-macos.
So remove that dependency.
Contributes to https://github.com/nix-community/poetry2nix/issues/1609.
Feel free to do changes, request changes or reject this PR as you wish. 
> Remove implicit tensorflow-macos dependency on tensorflow

- overrides/build-systems.json
- overrides/default.nix
Numpy switched build systems.
Fixes #1708.
> overrides: numpy 2

- overrides/default.nix
- tests/pyogrio/default.nix
Fixes python 3.10 build for pyogrio, which requires tomli in that case.
> fix(pyogrio): fix python 3.10 builds

- flake.nix
Hello there 👋!
The NixOS wiki is in the process of migrating from https://nixos.wiki to https://wiki.nixos.org.
You can find more information about it [here](https://github.com/NixOS/foundation/issues/113).
You seem to be using the old link in your repository, which is why we send you this PR.
If you feel like this is not correct or have any questions, feel free to [get in touch with us](https://github.com/NixOS/nixos-wiki-infra/issues/105).
Have a great day,
-- The NixOS Wiki-Team ❄️
> Update NixOS Wiki link

- overrides/build-systems.json
> Add iterpy, monoyed and launchdarkly to overrides build systems

- overrides/build-systems.json
> overrides: add pymediawiki (needs setuptools)

- overrides/build-systems.json
> overrides: add types-polib (needs setuptools)

- overrides/default.nix
adds hashes for `ruff`:
- 0.5.2
- 0.5.3
- 0.5.4
- 0.5.5
> overrides: update ruff hashes

- overrides/default.nix
> overrides: add cargo hash for bcrypt 4.2.0

- overrides/build-systems.json
> overrides: add hikari-lightbulb (needs flit)

- overrides/build-systems.json
sqlmodel migrated from Poetry to PDM with:
https://github.com/tiangolo/sqlmodel/pull/912
> fix(overrides): sqlmodel: switch to pdm

- docs/edgecases.md
- overrides/build-systems.json
> overrides: sse-starlette switch to pdm-backend

- README.md
It seems like this changed ages ago but the docs didn't. Perhaps there are other places that need changing too.
Also used a non-deprecated (3.9) example Python version to go to
> Update README to use newer `python3` attribute

- overrides/default.nix
Somewhere between nixpkgs 693bc46d169f5af9c992095736e82c3488bf7dbb and 52ec9ac3b12395ad677e8b62106f0b98c1f8569d, lxml stopped building because it could no longer use zlib as pulled in by one of its dependencies (perhaps Python itself?)
> fix(lxml): Add missing zlib dependency

- overrides/default.nix
This package is marked as broken and is unnecessary.
Per @RCoeurjoly in https://github.com/nix-community/poetry2nix/issues/1607#issuecomment-2067734269_
Note that according to https://pypi.org/project/setuptools-scm-git-archive/
This plugin is obsolete. ``setuptools_scm >= 7.0.0`` supports Git archives by itself.
> fix(jira): drop setuptools-scm-git-archive

- overrides/default.nix
> overrides: Disable fortify during build of msgspec to avoid SIGABRT during JSON generation

- overrides/build-systems.json
Add the nmcli package which only requires setuptools
> overrides: Add nmcli package

- overrides/build-systems.json
- overrides/default.nix
> overrides: add objprint, pye3d and viztracer

- overrides/default.nix
- tests/canonical-module-names/default.nix
A lot of tests failed when using `--replace-fail`, which probably means that the replacements only apply to other versions than the ones used in the tests. This can easily happen if there are overrides for two packages with a dependency between them, since they probably won't build the exact same versions.
> fix: Use non-deprecated replacement arguments

- overrides/default.nix
---
This PR fixes the following error:
```
error: builder for '/nix/store/v1bz2vfmfapa4h986gz26sg214sw8559-python3.12-imagecodecs-2024.6.1.drv' failed with exit code 2;
> Using pypaInstallPhase
> Sourcing python-imports-check-hook.sh
> Using pythonImportsCheckPhase
> Sourcing python-namespaces-hook
> Sourcing python-catch-conflicts-hook.sh
> Running phase: unpackPhase
> Executing wheelUnpackPhase
> Finished executing wheelUnpackPhase
> Running phase: patchPhase
> /nix/store/hix7sl0wxajb5aq14afjdvzc3w0i8b14-stdenv-linux/setup: eval: line 1716: unexpected EOF while looking for matching `"
'
For full logs, run 'nix log …
```
> overrides: fix patch for imagecodecs

- overrides/build-systems.json
When trying to migrate a large Django project I have to nix I ran into errors for builds here. I tested this by pointing my Django project at my local directory while developing and adding the required build systems for each package.
> fix(overrides): update build systems for a handful of django packages

- overrides/build-systems.json
Fixes https://github.com/nix-community/poetry2nix/issues/1807
> fix(overrides): urllib3 now dependes on hatch-vcs

- overrides/build-systems.json
See: https://github.com/BoboTiG/python-mss/releases/tag/v9.0.2
> overrides: add mss 9.0.2+, ffmpegcv

- flake.nix
- overrides/default.nix
- tests/pyside6/default.nix
- tests/pyside6/pyproject.toml
- tests/pyside6/test_pyside6/__init__.py
Fixes https://github.com/nix-community/poetry2nix/issues/1791
> pyside6: ensure PySide6 can be imported and used

- overrides/build-systems.json
Explanation:
- `pycairo` uses `meson-python` [as of 1.27.0](https://github.com/pygobject/pycairo/compare/v1.26.1...v1.27.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).
- `meson-python` has [basically always](https://github.com/mesonbuild/meson-python/blob/0.1.0/pyproject.toml) required `meson` and `ninja`. It also depends on `pyproject-metadata` but that seems to work without overrides.
- `pyproject-metadata` uses `flit-core` [as of 0.8.0](https://github.com/pypa/pyproject-metadata/compare/0.7.1...0.8.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711).
> fix(overrides): migrate pycairo to meson-python (and fix dependencies)

- overrides/build-systems.json
looks like since yesterday yarl (used by aiohttp) needs this package and next version of aiohttp will depend on it as well
> fix(overrides): propcache

- overrides/build-systems.json
> fix(overrides): logging-json uses setuptools

- overrides/default.nix
Need `attrdict`,`sip` to build wxpython 4.2.0
> overrides wxpython

- overrides/build-systems.json
add overrides for kubernetes-validate, os-client-config and sphinx-multiversion
> Add overrides for kubernetes-validate, os-client-config and sphinx-multiversion

- overrides/build-systems.json
Sorry for the "it works for my machine" but I don't think it get any more complicated than this
<details>
<summary>Original error</summary>
```
error: builder for '/nix/store/hqm1fpycm4q5arr9bksa22ly207rrcha-python3.12-luaparser-3.2.1.drv' failed with exit code 2;
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>   File "<frozen importlib._bootstrap>", line …
```
> feat(luaparser): override build-systems

- default.nix
Poetry documentation on dependency groups [1] says:
"The dependencies declared in tool.poetry.dependencies are part of an
implicit main group."
The current implementation does not account for that and in particular does not allow to skip installation of default dependencies like in one of
`poetry install --without main`
`poetry install --only-root`
`poetry install --only othergroup`.
This commit adds main as an implicit group and also adds it as a default value where applicable.
[1]
https://python-poetry.org/docs/managing-dependencies#dependency-groups
Closes #1578
> Treat default dependencies as main group

- flake.lock
- overrides/default.nix
- **fix(pyzmq): add new libsodium runtime dependency**
- **chore: remove use of now-invalid override of tokenizers**
- **chore: remove use of now-invalid override from pyqt6**
- **chore: work around missing optional-dependencies attribute**
- **chore(deps): bump nix-github-actions**
- **chore(deps): bump nixpkgs**
- **chore(deps): bump treefmt-nix**
> chore(deps): bump flakes

- .github/PULL_REQUEST_TEMPLATE.md
The links in the PR template don't work. This fixes it.
Before:
---
---
After:
---
> update links in the pull request template for contributing and automated tests

- overrides/default.nix
Clean the `__pycache__` folder to avoid collisions between `pyside6`, `pyside6-addons`, and `pyside6-essentials`.
Related to: https://github.com/nix-community/poetry2nix/pull/1808
> overrides: fix pyside6

- flake.lock
- flake.nix
Removes the leaked indirect `inputs.systems`. This created an ambiguous and indirect lockfile entry, this is resolved with this PR, which creates a clear `original` entry with fields similar to the `locked` entry. 
Furthermore, not having it marked as an input is not inline with the examples of the `nix-systems` project found [here](https://github.com/nix-systems/nix-systems/blob/main/examples/simple/flake.nix#L4). 
> Remove Leaked `indirect` Input

- overrides/build-systems.json
* icalendar uses hatchling/hatch-vcs since 6.0.0
* `until` version constraints in `build-systems.json` are _exclusive_, so isort 5.13.2 was broken after change b0b33d45
> overrides: Fix isort 5.13.2; Add icalendar 6.0.0
